// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package core

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// =================================================================
//
//	API Gateway 基础数据类型定义
//
// =================================================================
type UUID = string

type TimestampMS = int64

type URL = string

type IPAddress = string

// =================================================================
//                          请求上下文
// =================================================================
/**
 * 请求上下文 - 所有请求的核心上下文信息
 * 这是整个系统中传递的核心数据结构
 * 字段顺序与现有Context中间件保持一致
 */
type RequestContext struct {
	// 追踪信息 - 核心标识符
	RequestID *string `thrift:"requestID,1,optional" form:"requestID" json:"requestID,omitempty" query:"requestID"`
	// 链路追踪标识
	TraceID *string `thrift:"traceID,2,optional" form:"traceID" json:"traceID,omitempty" query:"traceID"`
	// 请求发起时间 (Unix毫秒)
	RequestTime *TimestampMS `thrift:"requestTime,3,optional" form:"requestTime" json:"requestTime,omitempty" query:"requestTime"`
	// 客户端信息
	ClientIP *string `thrift:"clientIP,4,optional" form:"clientIP" json:"clientIP,omitempty" query:"clientIP"`
	// 用户代理字符串
	UserAgent *string `thrift:"userAgent,5,optional" form:"userAgent" json:"userAgent,omitempty" query:"userAgent"`
	// 从认证信息中提炼出的、对所有服务都有用的核心身份
	UserID *string `thrift:"userID,6,optional" form:"userID" json:"userID,omitempty" query:"userID"`
	// 组织ID
	OrganizationID *string `thrift:"organizationID,7,optional" form:"organizationID" json:"organizationID,omitempty" query:"organizationID"`
	// 租户ID
	TenantID *string `thrift:"tenantID,8,optional" form:"tenantID" json:"tenantID,omitempty" query:"tenantID"`
	// 其他信息
	Source *string `thrift:"source,9,optional" form:"source" json:"source,omitempty" query:"source"`
	// 语言环境 (zh-CN|en-US)
	Locale *string `thrift:"locale,10,optional" form:"locale" json:"locale,omitempty" query:"locale"`
	// 扩展字段
	Metadata map[string]string `thrift:"metadata,11,optional" form:"metadata" json:"metadata,omitempty" query:"metadata"`
}

func NewRequestContext() *RequestContext {
	return &RequestContext{}
}

func (p *RequestContext) InitDefault() {
}

var RequestContext_RequestID_DEFAULT string

func (p *RequestContext) GetRequestID() (v string) {
	if !p.IsSetRequestID() {
		return RequestContext_RequestID_DEFAULT
	}
	return *p.RequestID
}

var RequestContext_TraceID_DEFAULT string

func (p *RequestContext) GetTraceID() (v string) {
	if !p.IsSetTraceID() {
		return RequestContext_TraceID_DEFAULT
	}
	return *p.TraceID
}

var RequestContext_RequestTime_DEFAULT TimestampMS

func (p *RequestContext) GetRequestTime() (v TimestampMS) {
	if !p.IsSetRequestTime() {
		return RequestContext_RequestTime_DEFAULT
	}
	return *p.RequestTime
}

var RequestContext_ClientIP_DEFAULT string

func (p *RequestContext) GetClientIP() (v string) {
	if !p.IsSetClientIP() {
		return RequestContext_ClientIP_DEFAULT
	}
	return *p.ClientIP
}

var RequestContext_UserAgent_DEFAULT string

func (p *RequestContext) GetUserAgent() (v string) {
	if !p.IsSetUserAgent() {
		return RequestContext_UserAgent_DEFAULT
	}
	return *p.UserAgent
}

var RequestContext_UserID_DEFAULT string

func (p *RequestContext) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return RequestContext_UserID_DEFAULT
	}
	return *p.UserID
}

var RequestContext_OrganizationID_DEFAULT string

func (p *RequestContext) GetOrganizationID() (v string) {
	if !p.IsSetOrganizationID() {
		return RequestContext_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var RequestContext_TenantID_DEFAULT string

func (p *RequestContext) GetTenantID() (v string) {
	if !p.IsSetTenantID() {
		return RequestContext_TenantID_DEFAULT
	}
	return *p.TenantID
}

var RequestContext_Source_DEFAULT string

func (p *RequestContext) GetSource() (v string) {
	if !p.IsSetSource() {
		return RequestContext_Source_DEFAULT
	}
	return *p.Source
}

var RequestContext_Locale_DEFAULT string

func (p *RequestContext) GetLocale() (v string) {
	if !p.IsSetLocale() {
		return RequestContext_Locale_DEFAULT
	}
	return *p.Locale
}

var RequestContext_Metadata_DEFAULT map[string]string

func (p *RequestContext) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return RequestContext_Metadata_DEFAULT
	}
	return p.Metadata
}

var fieldIDToName_RequestContext = map[int16]string{
	1:  "requestID",
	2:  "traceID",
	3:  "requestTime",
	4:  "clientIP",
	5:  "userAgent",
	6:  "userID",
	7:  "organizationID",
	8:  "tenantID",
	9:  "source",
	10: "locale",
	11: "metadata",
}

func (p *RequestContext) IsSetRequestID() bool {
	return p.RequestID != nil
}

func (p *RequestContext) IsSetTraceID() bool {
	return p.TraceID != nil
}

func (p *RequestContext) IsSetRequestTime() bool {
	return p.RequestTime != nil
}

func (p *RequestContext) IsSetClientIP() bool {
	return p.ClientIP != nil
}

func (p *RequestContext) IsSetUserAgent() bool {
	return p.UserAgent != nil
}

func (p *RequestContext) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *RequestContext) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *RequestContext) IsSetTenantID() bool {
	return p.TenantID != nil
}

func (p *RequestContext) IsSetSource() bool {
	return p.Source != nil
}

func (p *RequestContext) IsSetLocale() bool {
	return p.Locale != nil
}

func (p *RequestContext) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *RequestContext) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 10:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField10(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 11:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField11(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_RequestContext[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *RequestContext) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.RequestID = _field
	return nil
}
func (p *RequestContext) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.TraceID = _field
	return nil
}
func (p *RequestContext) ReadField3(iprot thrift.TProtocol) error {

	var _field *TimestampMS
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.RequestTime = _field
	return nil
}
func (p *RequestContext) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ClientIP = _field
	return nil
}
func (p *RequestContext) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UserAgent = _field
	return nil
}
func (p *RequestContext) ReadField6(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UserID = _field
	return nil
}
func (p *RequestContext) ReadField7(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.OrganizationID = _field
	return nil
}
func (p *RequestContext) ReadField8(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.TenantID = _field
	return nil
}
func (p *RequestContext) ReadField9(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Source = _field
	return nil
}
func (p *RequestContext) ReadField10(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Locale = _field
	return nil
}
func (p *RequestContext) ReadField11(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	_field := make(map[string]string, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}

		var _val string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_val = v
		}

		_field[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	p.Metadata = _field
	return nil
}

func (p *RequestContext) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("RequestContext"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
		if err = p.writeField10(oprot); err != nil {
			fieldId = 10
			goto WriteFieldError
		}
		if err = p.writeField11(oprot); err != nil {
			fieldId = 11
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *RequestContext) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetRequestID() {
		if err = oprot.WriteFieldBegin("requestID", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.RequestID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *RequestContext) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetTraceID() {
		if err = oprot.WriteFieldBegin("traceID", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.TraceID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *RequestContext) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetRequestTime() {
		if err = oprot.WriteFieldBegin("requestTime", thrift.I64, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.RequestTime); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *RequestContext) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetClientIP() {
		if err = oprot.WriteFieldBegin("clientIP", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ClientIP); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *RequestContext) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetUserAgent() {
		if err = oprot.WriteFieldBegin("userAgent", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UserAgent); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *RequestContext) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetUserID() {
		if err = oprot.WriteFieldBegin("userID", thrift.STRING, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UserID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *RequestContext) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetOrganizationID() {
		if err = oprot.WriteFieldBegin("organizationID", thrift.STRING, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.OrganizationID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *RequestContext) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetTenantID() {
		if err = oprot.WriteFieldBegin("tenantID", thrift.STRING, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.TenantID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *RequestContext) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetSource() {
		if err = oprot.WriteFieldBegin("source", thrift.STRING, 9); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Source); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}

func (p *RequestContext) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetLocale() {
		if err = oprot.WriteFieldBegin("locale", thrift.STRING, 10); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Locale); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 end error: ", p), err)
}

func (p *RequestContext) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetMetadata() {
		if err = oprot.WriteFieldBegin("metadata", thrift.MAP, 11); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.Metadata)); err != nil {
			return err
		}
		for k, v := range p.Metadata {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 end error: ", p), err)
}

func (p *RequestContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestContext(%+v)", *p)

}
