// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package rpc_base

import (
	"fmt"
)

type PageRequest struct {
	Page         int32             `thrift:"page,1,optional" frugal:"1,optional,i32" json:"page,omitempty"`
	Limit        int32             `thrift:"limit,2,optional" frugal:"2,optional,i32" json:"limit,omitempty"`
	Search       *string           `thrift:"search,3,optional" frugal:"3,optional,string" json:"search,omitempty"`
	Filter       map[string]string `thrift:"filter,4,optional" frugal:"4,optional,map<string:string>" json:"filter,omitempty"`
	Sort         *string           `thrift:"sort,5,optional" frugal:"5,optional,string" json:"sort,omitempty"`
	Fields       []string          `thrift:"fields,6,optional" frugal:"6,optional,list<string>" json:"fields,omitempty"`
	IncludeTotal *bool             `thrift:"include_total,7,optional" frugal:"7,optional,bool" json:"include_total,omitempty"`
	FetchAll     *bool             `thrift:"fetch_all,8,optional" frugal:"8,optional,bool" json:"fetch_all,omitempty"`
}

func NewPageRequest() *PageRequest {
	return &PageRequest{
		Page:  1,
		Limit: 20,
	}
}

func (p *PageRequest) InitDefault() {
	p.Page = 1
	p.Limit = 20
}

var PageRequest_Page_DEFAULT int32 = 1

func (p *PageRequest) GetPage() (v int32) {
	if !p.IsSetPage() {
		return PageRequest_Page_DEFAULT
	}
	return p.Page
}

var PageRequest_Limit_DEFAULT int32 = 20

func (p *PageRequest) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return PageRequest_Limit_DEFAULT
	}
	return p.Limit
}

var PageRequest_Search_DEFAULT string

func (p *PageRequest) GetSearch() (v string) {
	if !p.IsSetSearch() {
		return PageRequest_Search_DEFAULT
	}
	return *p.Search
}

var PageRequest_Filter_DEFAULT map[string]string

func (p *PageRequest) GetFilter() (v map[string]string) {
	if !p.IsSetFilter() {
		return PageRequest_Filter_DEFAULT
	}
	return p.Filter
}

var PageRequest_Sort_DEFAULT string

func (p *PageRequest) GetSort() (v string) {
	if !p.IsSetSort() {
		return PageRequest_Sort_DEFAULT
	}
	return *p.Sort
}

var PageRequest_Fields_DEFAULT []string

func (p *PageRequest) GetFields() (v []string) {
	if !p.IsSetFields() {
		return PageRequest_Fields_DEFAULT
	}
	return p.Fields
}

var PageRequest_IncludeTotal_DEFAULT bool

func (p *PageRequest) GetIncludeTotal() (v bool) {
	if !p.IsSetIncludeTotal() {
		return PageRequest_IncludeTotal_DEFAULT
	}
	return *p.IncludeTotal
}

var PageRequest_FetchAll_DEFAULT bool

func (p *PageRequest) GetFetchAll() (v bool) {
	if !p.IsSetFetchAll() {
		return PageRequest_FetchAll_DEFAULT
	}
	return *p.FetchAll
}
func (p *PageRequest) SetPage(val int32) {
	p.Page = val
}
func (p *PageRequest) SetLimit(val int32) {
	p.Limit = val
}
func (p *PageRequest) SetSearch(val *string) {
	p.Search = val
}
func (p *PageRequest) SetFilter(val map[string]string) {
	p.Filter = val
}
func (p *PageRequest) SetSort(val *string) {
	p.Sort = val
}
func (p *PageRequest) SetFields(val []string) {
	p.Fields = val
}
func (p *PageRequest) SetIncludeTotal(val *bool) {
	p.IncludeTotal = val
}
func (p *PageRequest) SetFetchAll(val *bool) {
	p.FetchAll = val
}

func (p *PageRequest) IsSetPage() bool {
	return p.Page != PageRequest_Page_DEFAULT
}

func (p *PageRequest) IsSetLimit() bool {
	return p.Limit != PageRequest_Limit_DEFAULT
}

func (p *PageRequest) IsSetSearch() bool {
	return p.Search != nil
}

func (p *PageRequest) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *PageRequest) IsSetSort() bool {
	return p.Sort != nil
}

func (p *PageRequest) IsSetFields() bool {
	return p.Fields != nil
}

func (p *PageRequest) IsSetIncludeTotal() bool {
	return p.IncludeTotal != nil
}

func (p *PageRequest) IsSetFetchAll() bool {
	return p.FetchAll != nil
}

func (p *PageRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequest(%+v)", *p)
}

var fieldIDToName_PageRequest = map[int16]string{
	1: "page",
	2: "limit",
	3: "search",
	4: "filter",
	5: "sort",
	6: "fields",
	7: "include_total",
	8: "fetch_all",
}

type PageResponse struct {
	Total      *int32 `thrift:"total,1,optional" frugal:"1,optional,i32" json:"total,omitempty"`
	Page       *int32 `thrift:"page,2,optional" frugal:"2,optional,i32" json:"page,omitempty"`
	Limit      *int32 `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
	TotalPages *int32 `thrift:"total_pages,4,optional" frugal:"4,optional,i32" json:"total_pages,omitempty"`
	HasNext    *bool  `thrift:"has_next,5,optional" frugal:"5,optional,bool" json:"has_next,omitempty"`
	HasPrev    *bool  `thrift:"has_prev,6,optional" frugal:"6,optional,bool" json:"has_prev,omitempty"`
}

func NewPageResponse() *PageResponse {
	return &PageResponse{}
}

func (p *PageResponse) InitDefault() {
}

var PageResponse_Total_DEFAULT int32

func (p *PageResponse) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return PageResponse_Total_DEFAULT
	}
	return *p.Total
}

var PageResponse_Page_DEFAULT int32

func (p *PageResponse) GetPage() (v int32) {
	if !p.IsSetPage() {
		return PageResponse_Page_DEFAULT
	}
	return *p.Page
}

var PageResponse_Limit_DEFAULT int32

func (p *PageResponse) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return PageResponse_Limit_DEFAULT
	}
	return *p.Limit
}

var PageResponse_TotalPages_DEFAULT int32

func (p *PageResponse) GetTotalPages() (v int32) {
	if !p.IsSetTotalPages() {
		return PageResponse_TotalPages_DEFAULT
	}
	return *p.TotalPages
}

var PageResponse_HasNext_DEFAULT bool

func (p *PageResponse) GetHasNext() (v bool) {
	if !p.IsSetHasNext() {
		return PageResponse_HasNext_DEFAULT
	}
	return *p.HasNext
}

var PageResponse_HasPrev_DEFAULT bool

func (p *PageResponse) GetHasPrev() (v bool) {
	if !p.IsSetHasPrev() {
		return PageResponse_HasPrev_DEFAULT
	}
	return *p.HasPrev
}
func (p *PageResponse) SetTotal(val *int32) {
	p.Total = val
}
func (p *PageResponse) SetPage(val *int32) {
	p.Page = val
}
func (p *PageResponse) SetLimit(val *int32) {
	p.Limit = val
}
func (p *PageResponse) SetTotalPages(val *int32) {
	p.TotalPages = val
}
func (p *PageResponse) SetHasNext(val *bool) {
	p.HasNext = val
}
func (p *PageResponse) SetHasPrev(val *bool) {
	p.HasPrev = val
}

func (p *PageResponse) IsSetTotal() bool {
	return p.Total != nil
}

func (p *PageResponse) IsSetPage() bool {
	return p.Page != nil
}

func (p *PageResponse) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *PageResponse) IsSetTotalPages() bool {
	return p.TotalPages != nil
}

func (p *PageResponse) IsSetHasNext() bool {
	return p.HasNext != nil
}

func (p *PageResponse) IsSetHasPrev() bool {
	return p.HasPrev != nil
}

func (p *PageResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResponse(%+v)", *p)
}

var fieldIDToName_PageResponse = map[int16]string{
	1: "total",
	2: "page",
	3: "limit",
	4: "total_pages",
	5: "has_next",
	6: "has_prev",
}
