// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	identity "github.com/masonsxu/cloudwego-scaffold/gateway/biz/router/identity"
	permission "github.com/masonsxu/cloudwego-scaffold/gateway/biz/router/permission"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	permission.Register(r)

	identity.Register(r)
}
