// Code generated by hertz generator.

package main

import (
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/etag"
	"github.com/hertz-contrib/requestid"
	identityHandler "github.com/masonsxu/cloudwego-scaffold/gateway/biz/handler/identity"
	permissionHandler "github.com/masonsxu/cloudwego-scaffold/gateway/biz/handler/permission"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/application/middleware"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/wire"
)

// 保留空实现以满足生成代码引用 app 包
var _ app.HandlerFunc

func main() {
	// init config
	config := wire.ProvideConfig()

	// init service
	services, err := wire.InitializeService()
	if err != nil {
		log.Fatalf("failed to init app: %v", err)
	}

	// init middlewares
	middlewares, err := wire.InitializeMiddleware()
	if err != nil {
		log.Fatalf("failed to init middlewares: %v", err)
	}

	// init server
	addr := fmt.Sprintf("%s:%s", config.Server.Host, config.Server.Port)
	h := server.New(server.WithHostPorts(addr), server.WithMaxRequestBodySize(100*1024*1024))
	// 使用 etag 中间件
	h.Use(etag.New())
	// 使用 requestid 中间件（必须在 trace_middleware 之前）
	// requestid 中间件会自动从 X-Request-ID header 获取或生成 requestID，并添加到响应头中
	h.Use(requestid.New())

	// 初始化中间件（不包含 Casbin 全局中间件）
	middleware.DefaultMiddleware(
		h,
		middlewares.TraceMiddleware,
		middlewares.CORSMiddleware,
		middlewares.ErrorHandlerMiddleware,
		middlewares.JWTMiddleware,
	)

	// 设置全局 Casbin 中间件实例，供路由中间件使用
	// middleware.SetGlobalCasbinMiddleware(middlewares.CasbinMiddleware)

	// 初始化handler层的服务实例
	identityHandler.SetIdentityService(services.IdentityService, middlewares.JWTMiddleware)
	permissionHandler.SetPermissionService(services.PermissionService)

	// 使用 services 变量确保其被使用
	_ = services

	register(h)
	h.Spin()
}
