// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	handler "github.com/masonsxu/cloudwego-scaffold/gateway/biz/handler"
	_ "github.com/masonsxu/cloudwego-scaffold/gateway/docs"
	swaggerFiles "github.com/swaggo/files"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// Swagger API 文档
	// 从配置中获取服务地址，避免使用固定的localhost
	url := swagger.URL("doc.json")
	r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, url))
}
