// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package identity_srv

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/core"
)

type OrganizationLogoStatus int64

const (
	OrganizationLogoStatus_TEMPORARY OrganizationLogoStatus = 0
	OrganizationLogoStatus_BOUND     OrganizationLogoStatus = 1
	OrganizationLogoStatus_DELETED   OrganizationLogoStatus = 2
)

func (p OrganizationLogoStatus) String() string {
	switch p {
	case OrganizationLogoStatus_TEMPORARY:
		return "TEMPORARY"
	case OrganizationLogoStatus_BOUND:
		return "BOUND"
	case OrganizationLogoStatus_DELETED:
		return "DELETED"
	}
	return "<UNSET>"
}

func OrganizationLogoStatusFromString(s string) (OrganizationLogoStatus, error) {
	switch s {
	case "TEMPORARY":
		return OrganizationLogoStatus_TEMPORARY, nil
	case "BOUND":
		return OrganizationLogoStatus_BOUND, nil
	case "DELETED":
		return OrganizationLogoStatus_DELETED, nil
	}
	return OrganizationLogoStatus(0), fmt.Errorf("not a valid OrganizationLogoStatus string")
}

func OrganizationLogoStatusPtr(v OrganizationLogoStatus) *OrganizationLogoStatus { return &v }
func (p *OrganizationLogoStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OrganizationLogoStatus(result.Int64)
	return
}

func (p *OrganizationLogoStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type UserProfile struct {
	ID                    *core.UUID        `thrift:"ID,1,optional" frugal:"1,optional,string" json:"ID,omitempty"`
	Username              *string           `thrift:"username,2,optional" frugal:"2,optional,string" json:"username,omitempty"`
	Email                 *string           `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
	Phone                 *string           `thrift:"phone,4,optional" frugal:"4,optional,string" json:"phone,omitempty"`
	FirstName             *string           `thrift:"firstName,5,optional" frugal:"5,optional,string" json:"firstName,omitempty"`
	LastName              *string           `thrift:"lastName,6,optional" frugal:"6,optional,string" json:"lastName,omitempty"`
	RealName              *string           `thrift:"realName,7,optional" frugal:"7,optional,string" json:"realName,omitempty"`
	Gender                *core.Gender      `thrift:"gender,26,optional" frugal:"26,optional,Gender" json:"gender,omitempty"`
	ProfessionalTitle     *string           `thrift:"professionalTitle,8,optional" frugal:"8,optional,string" json:"professionalTitle,omitempty"`
	LicenseNumber         *string           `thrift:"licenseNumber,9,optional" frugal:"9,optional,string" json:"licenseNumber,omitempty"`
	Specialties           []string          `thrift:"specialties,10,optional" frugal:"10,optional,list<string>" json:"specialties,omitempty"`
	EmployeeID            *string           `thrift:"employeeID,11,optional" frugal:"11,optional,string" json:"employeeID,omitempty"`
	Status                *core.UserStatus  `thrift:"status,12,optional" frugal:"12,optional,UserStatus" json:"status,omitempty"`
	LoginAttempts         int32             `thrift:"loginAttempts,13,optional" frugal:"13,optional,i32" json:"loginAttempts,omitempty"`
	MustChangePassword    bool              `thrift:"mustChangePassword,14,optional" frugal:"14,optional,bool" json:"mustChangePassword,omitempty"`
	AccountExpiry         *core.TimestampMS `thrift:"accountExpiry,15,optional" frugal:"15,optional,i64" json:"accountExpiry,omitempty"`
	LastLoginTime         *core.TimestampMS `thrift:"lastLoginTime,20,optional" frugal:"20,optional,i64" json:"lastLoginTime,omitempty"`
	CreatedAt             *core.TimestampMS `thrift:"createdAt,16,optional" frugal:"16,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt             *core.TimestampMS `thrift:"updatedAt,17,optional" frugal:"17,optional,i64" json:"updatedAt,omitempty"`
	CreatedBy             *core.UUID        `thrift:"createdBy,18,optional" frugal:"18,optional,string" json:"createdBy,omitempty"`
	UpdatedBy             *core.UUID        `thrift:"updatedBy,19,optional" frugal:"19,optional,string" json:"updatedBy,omitempty"`
	Version               int32             `thrift:"version,21,optional" frugal:"21,optional,i32" json:"version,omitempty"`
	Deleted               bool              `thrift:"deleted,22,optional" frugal:"22,optional,bool" json:"deleted,omitempty"`
	RoleIDs               []core.UUID       `thrift:"roleIDs,23,optional" frugal:"23,optional,list<string>" json:"roleIDs,omitempty"`
	PrimaryOrganizationID *core.UUID        `thrift:"primaryOrganizationID,24,optional" frugal:"24,optional,string" json:"primaryOrganizationID,omitempty"`
	PrimaryDepartmentID   *core.UUID        `thrift:"primaryDepartmentID,25,optional" frugal:"25,optional,string" json:"primaryDepartmentID,omitempty"`
}

func NewUserProfile() *UserProfile {
	return &UserProfile{
		LoginAttempts:      0,
		MustChangePassword: false,
		Version:            1,
		Deleted:            false,
	}
}

func (p *UserProfile) InitDefault() {
	p.LoginAttempts = 0
	p.MustChangePassword = false
	p.Version = 1
	p.Deleted = false
}

var UserProfile_ID_DEFAULT core.UUID

func (p *UserProfile) GetID() (v core.UUID) {
	if !p.IsSetID() {
		return UserProfile_ID_DEFAULT
	}
	return *p.ID
}

var UserProfile_Username_DEFAULT string

func (p *UserProfile) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return UserProfile_Username_DEFAULT
	}
	return *p.Username
}

var UserProfile_Email_DEFAULT string

func (p *UserProfile) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return UserProfile_Email_DEFAULT
	}
	return *p.Email
}

var UserProfile_Phone_DEFAULT string

func (p *UserProfile) GetPhone() (v string) {
	if !p.IsSetPhone() {
		return UserProfile_Phone_DEFAULT
	}
	return *p.Phone
}

var UserProfile_FirstName_DEFAULT string

func (p *UserProfile) GetFirstName() (v string) {
	if !p.IsSetFirstName() {
		return UserProfile_FirstName_DEFAULT
	}
	return *p.FirstName
}

var UserProfile_LastName_DEFAULT string

func (p *UserProfile) GetLastName() (v string) {
	if !p.IsSetLastName() {
		return UserProfile_LastName_DEFAULT
	}
	return *p.LastName
}

var UserProfile_RealName_DEFAULT string

func (p *UserProfile) GetRealName() (v string) {
	if !p.IsSetRealName() {
		return UserProfile_RealName_DEFAULT
	}
	return *p.RealName
}

var UserProfile_Gender_DEFAULT core.Gender

func (p *UserProfile) GetGender() (v core.Gender) {
	if !p.IsSetGender() {
		return UserProfile_Gender_DEFAULT
	}
	return *p.Gender
}

var UserProfile_ProfessionalTitle_DEFAULT string

func (p *UserProfile) GetProfessionalTitle() (v string) {
	if !p.IsSetProfessionalTitle() {
		return UserProfile_ProfessionalTitle_DEFAULT
	}
	return *p.ProfessionalTitle
}

var UserProfile_LicenseNumber_DEFAULT string

func (p *UserProfile) GetLicenseNumber() (v string) {
	if !p.IsSetLicenseNumber() {
		return UserProfile_LicenseNumber_DEFAULT
	}
	return *p.LicenseNumber
}

var UserProfile_Specialties_DEFAULT []string

func (p *UserProfile) GetSpecialties() (v []string) {
	if !p.IsSetSpecialties() {
		return UserProfile_Specialties_DEFAULT
	}
	return p.Specialties
}

var UserProfile_EmployeeID_DEFAULT string

func (p *UserProfile) GetEmployeeID() (v string) {
	if !p.IsSetEmployeeID() {
		return UserProfile_EmployeeID_DEFAULT
	}
	return *p.EmployeeID
}

var UserProfile_Status_DEFAULT core.UserStatus

func (p *UserProfile) GetStatus() (v core.UserStatus) {
	if !p.IsSetStatus() {
		return UserProfile_Status_DEFAULT
	}
	return *p.Status
}

var UserProfile_LoginAttempts_DEFAULT int32 = 0

func (p *UserProfile) GetLoginAttempts() (v int32) {
	if !p.IsSetLoginAttempts() {
		return UserProfile_LoginAttempts_DEFAULT
	}
	return p.LoginAttempts
}

var UserProfile_MustChangePassword_DEFAULT bool = false

func (p *UserProfile) GetMustChangePassword() (v bool) {
	if !p.IsSetMustChangePassword() {
		return UserProfile_MustChangePassword_DEFAULT
	}
	return p.MustChangePassword
}

var UserProfile_AccountExpiry_DEFAULT core.TimestampMS

func (p *UserProfile) GetAccountExpiry() (v core.TimestampMS) {
	if !p.IsSetAccountExpiry() {
		return UserProfile_AccountExpiry_DEFAULT
	}
	return *p.AccountExpiry
}

var UserProfile_LastLoginTime_DEFAULT core.TimestampMS

func (p *UserProfile) GetLastLoginTime() (v core.TimestampMS) {
	if !p.IsSetLastLoginTime() {
		return UserProfile_LastLoginTime_DEFAULT
	}
	return *p.LastLoginTime
}

var UserProfile_CreatedAt_DEFAULT core.TimestampMS

func (p *UserProfile) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return UserProfile_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var UserProfile_UpdatedAt_DEFAULT core.TimestampMS

func (p *UserProfile) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return UserProfile_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

var UserProfile_CreatedBy_DEFAULT core.UUID

func (p *UserProfile) GetCreatedBy() (v core.UUID) {
	if !p.IsSetCreatedBy() {
		return UserProfile_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var UserProfile_UpdatedBy_DEFAULT core.UUID

func (p *UserProfile) GetUpdatedBy() (v core.UUID) {
	if !p.IsSetUpdatedBy() {
		return UserProfile_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var UserProfile_Version_DEFAULT int32 = 1

func (p *UserProfile) GetVersion() (v int32) {
	if !p.IsSetVersion() {
		return UserProfile_Version_DEFAULT
	}
	return p.Version
}

var UserProfile_Deleted_DEFAULT bool = false

func (p *UserProfile) GetDeleted() (v bool) {
	if !p.IsSetDeleted() {
		return UserProfile_Deleted_DEFAULT
	}
	return p.Deleted
}

var UserProfile_RoleIDs_DEFAULT []core.UUID

func (p *UserProfile) GetRoleIDs() (v []core.UUID) {
	if !p.IsSetRoleIDs() {
		return UserProfile_RoleIDs_DEFAULT
	}
	return p.RoleIDs
}

var UserProfile_PrimaryOrganizationID_DEFAULT core.UUID

func (p *UserProfile) GetPrimaryOrganizationID() (v core.UUID) {
	if !p.IsSetPrimaryOrganizationID() {
		return UserProfile_PrimaryOrganizationID_DEFAULT
	}
	return *p.PrimaryOrganizationID
}

var UserProfile_PrimaryDepartmentID_DEFAULT core.UUID

func (p *UserProfile) GetPrimaryDepartmentID() (v core.UUID) {
	if !p.IsSetPrimaryDepartmentID() {
		return UserProfile_PrimaryDepartmentID_DEFAULT
	}
	return *p.PrimaryDepartmentID
}
func (p *UserProfile) SetID(val *core.UUID) {
	p.ID = val
}
func (p *UserProfile) SetUsername(val *string) {
	p.Username = val
}
func (p *UserProfile) SetEmail(val *string) {
	p.Email = val
}
func (p *UserProfile) SetPhone(val *string) {
	p.Phone = val
}
func (p *UserProfile) SetFirstName(val *string) {
	p.FirstName = val
}
func (p *UserProfile) SetLastName(val *string) {
	p.LastName = val
}
func (p *UserProfile) SetRealName(val *string) {
	p.RealName = val
}
func (p *UserProfile) SetGender(val *core.Gender) {
	p.Gender = val
}
func (p *UserProfile) SetProfessionalTitle(val *string) {
	p.ProfessionalTitle = val
}
func (p *UserProfile) SetLicenseNumber(val *string) {
	p.LicenseNumber = val
}
func (p *UserProfile) SetSpecialties(val []string) {
	p.Specialties = val
}
func (p *UserProfile) SetEmployeeID(val *string) {
	p.EmployeeID = val
}
func (p *UserProfile) SetStatus(val *core.UserStatus) {
	p.Status = val
}
func (p *UserProfile) SetLoginAttempts(val int32) {
	p.LoginAttempts = val
}
func (p *UserProfile) SetMustChangePassword(val bool) {
	p.MustChangePassword = val
}
func (p *UserProfile) SetAccountExpiry(val *core.TimestampMS) {
	p.AccountExpiry = val
}
func (p *UserProfile) SetLastLoginTime(val *core.TimestampMS) {
	p.LastLoginTime = val
}
func (p *UserProfile) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *UserProfile) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}
func (p *UserProfile) SetCreatedBy(val *core.UUID) {
	p.CreatedBy = val
}
func (p *UserProfile) SetUpdatedBy(val *core.UUID) {
	p.UpdatedBy = val
}
func (p *UserProfile) SetVersion(val int32) {
	p.Version = val
}
func (p *UserProfile) SetDeleted(val bool) {
	p.Deleted = val
}
func (p *UserProfile) SetRoleIDs(val []core.UUID) {
	p.RoleIDs = val
}
func (p *UserProfile) SetPrimaryOrganizationID(val *core.UUID) {
	p.PrimaryOrganizationID = val
}
func (p *UserProfile) SetPrimaryDepartmentID(val *core.UUID) {
	p.PrimaryDepartmentID = val
}

func (p *UserProfile) IsSetID() bool {
	return p.ID != nil
}

func (p *UserProfile) IsSetUsername() bool {
	return p.Username != nil
}

func (p *UserProfile) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UserProfile) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UserProfile) IsSetFirstName() bool {
	return p.FirstName != nil
}

func (p *UserProfile) IsSetLastName() bool {
	return p.LastName != nil
}

func (p *UserProfile) IsSetRealName() bool {
	return p.RealName != nil
}

func (p *UserProfile) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UserProfile) IsSetProfessionalTitle() bool {
	return p.ProfessionalTitle != nil
}

func (p *UserProfile) IsSetLicenseNumber() bool {
	return p.LicenseNumber != nil
}

func (p *UserProfile) IsSetSpecialties() bool {
	return p.Specialties != nil
}

func (p *UserProfile) IsSetEmployeeID() bool {
	return p.EmployeeID != nil
}

func (p *UserProfile) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UserProfile) IsSetLoginAttempts() bool {
	return p.LoginAttempts != UserProfile_LoginAttempts_DEFAULT
}

func (p *UserProfile) IsSetMustChangePassword() bool {
	return p.MustChangePassword != UserProfile_MustChangePassword_DEFAULT
}

func (p *UserProfile) IsSetAccountExpiry() bool {
	return p.AccountExpiry != nil
}

func (p *UserProfile) IsSetLastLoginTime() bool {
	return p.LastLoginTime != nil
}

func (p *UserProfile) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *UserProfile) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *UserProfile) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *UserProfile) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *UserProfile) IsSetVersion() bool {
	return p.Version != UserProfile_Version_DEFAULT
}

func (p *UserProfile) IsSetDeleted() bool {
	return p.Deleted != UserProfile_Deleted_DEFAULT
}

func (p *UserProfile) IsSetRoleIDs() bool {
	return p.RoleIDs != nil
}

func (p *UserProfile) IsSetPrimaryOrganizationID() bool {
	return p.PrimaryOrganizationID != nil
}

func (p *UserProfile) IsSetPrimaryDepartmentID() bool {
	return p.PrimaryDepartmentID != nil
}

func (p *UserProfile) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserProfile(%+v)", *p)
}

var fieldIDToName_UserProfile = map[int16]string{
	1:  "ID",
	2:  "username",
	3:  "email",
	4:  "phone",
	5:  "firstName",
	6:  "lastName",
	7:  "realName",
	26: "gender",
	8:  "professionalTitle",
	9:  "licenseNumber",
	10: "specialties",
	11: "employeeID",
	12: "status",
	13: "loginAttempts",
	14: "mustChangePassword",
	15: "accountExpiry",
	20: "lastLoginTime",
	16: "createdAt",
	17: "updatedAt",
	18: "createdBy",
	19: "updatedBy",
	21: "version",
	22: "deleted",
	23: "roleIDs",
	24: "primaryOrganizationID",
	25: "primaryDepartmentID",
}

type UserMembership struct {
	ID             *core.UUID        `thrift:"ID,1,optional" frugal:"1,optional,string" json:"ID,omitempty"`
	UserID         *core.UUID        `thrift:"userID,2,optional" frugal:"2,optional,string" json:"userID,omitempty"`
	OrganizationID *core.UUID        `thrift:"organizationID,3,optional" frugal:"3,optional,string" json:"organizationID,omitempty"`
	DepartmentID   *core.UUID        `thrift:"departmentID,4,optional" frugal:"4,optional,string" json:"departmentID,omitempty"`
	IsPrimary      *bool             `thrift:"isPrimary,5,optional" frugal:"5,optional,bool" json:"isPrimary,omitempty"`
	CreatedAt      *core.TimestampMS `thrift:"createdAt,6,optional" frugal:"6,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt      *core.TimestampMS `thrift:"updatedAt,7,optional" frugal:"7,optional,i64" json:"updatedAt,omitempty"`
}

func NewUserMembership() *UserMembership {
	return &UserMembership{}
}

func (p *UserMembership) InitDefault() {
}

var UserMembership_ID_DEFAULT core.UUID

func (p *UserMembership) GetID() (v core.UUID) {
	if !p.IsSetID() {
		return UserMembership_ID_DEFAULT
	}
	return *p.ID
}

var UserMembership_UserID_DEFAULT core.UUID

func (p *UserMembership) GetUserID() (v core.UUID) {
	if !p.IsSetUserID() {
		return UserMembership_UserID_DEFAULT
	}
	return *p.UserID
}

var UserMembership_OrganizationID_DEFAULT core.UUID

func (p *UserMembership) GetOrganizationID() (v core.UUID) {
	if !p.IsSetOrganizationID() {
		return UserMembership_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var UserMembership_DepartmentID_DEFAULT core.UUID

func (p *UserMembership) GetDepartmentID() (v core.UUID) {
	if !p.IsSetDepartmentID() {
		return UserMembership_DepartmentID_DEFAULT
	}
	return *p.DepartmentID
}

var UserMembership_IsPrimary_DEFAULT bool

func (p *UserMembership) GetIsPrimary() (v bool) {
	if !p.IsSetIsPrimary() {
		return UserMembership_IsPrimary_DEFAULT
	}
	return *p.IsPrimary
}

var UserMembership_CreatedAt_DEFAULT core.TimestampMS

func (p *UserMembership) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return UserMembership_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var UserMembership_UpdatedAt_DEFAULT core.TimestampMS

func (p *UserMembership) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return UserMembership_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *UserMembership) SetID(val *core.UUID) {
	p.ID = val
}
func (p *UserMembership) SetUserID(val *core.UUID) {
	p.UserID = val
}
func (p *UserMembership) SetOrganizationID(val *core.UUID) {
	p.OrganizationID = val
}
func (p *UserMembership) SetDepartmentID(val *core.UUID) {
	p.DepartmentID = val
}
func (p *UserMembership) SetIsPrimary(val *bool) {
	p.IsPrimary = val
}
func (p *UserMembership) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *UserMembership) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *UserMembership) IsSetID() bool {
	return p.ID != nil
}

func (p *UserMembership) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *UserMembership) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *UserMembership) IsSetDepartmentID() bool {
	return p.DepartmentID != nil
}

func (p *UserMembership) IsSetIsPrimary() bool {
	return p.IsPrimary != nil
}

func (p *UserMembership) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *UserMembership) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *UserMembership) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserMembership(%+v)", *p)
}

var fieldIDToName_UserMembership = map[int16]string{
	1: "ID",
	2: "userID",
	3: "organizationID",
	4: "departmentID",
	5: "isPrimary",
	6: "createdAt",
	7: "updatedAt",
}

type Organization struct {
	ID                  *core.UUID        `thrift:"ID,1,optional" frugal:"1,optional,string" json:"ID,omitempty"`
	Code                *string           `thrift:"code,2,optional" frugal:"2,optional,string" json:"code,omitempty"`
	Name                *string           `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	ParentID            *core.UUID        `thrift:"parentID,4,optional" frugal:"4,optional,string" json:"parentID,omitempty"`
	FacilityType        *string           `thrift:"facilityType,5,optional" frugal:"5,optional,string" json:"facilityType,omitempty"`
	AccreditationStatus *string           `thrift:"accreditationStatus,6,optional" frugal:"6,optional,string" json:"accreditationStatus,omitempty"`
	Logo                *string           `thrift:"logo,7,optional" frugal:"7,optional,string" json:"logo,omitempty"`
	LogoID              *core.UUID        `thrift:"logoID,15,optional" frugal:"15,optional,string" json:"logoID,omitempty"`
	ProvinceCity        []string          `thrift:"provinceCity,8,optional" frugal:"8,optional,list<string>" json:"provinceCity,omitempty"`
	CreatedAt           *core.TimestampMS `thrift:"createdAt,9,optional" frugal:"9,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt           *core.TimestampMS `thrift:"updatedAt,10,optional" frugal:"10,optional,i64" json:"updatedAt,omitempty"`
}

func NewOrganization() *Organization {
	return &Organization{}
}

func (p *Organization) InitDefault() {
}

var Organization_ID_DEFAULT core.UUID

func (p *Organization) GetID() (v core.UUID) {
	if !p.IsSetID() {
		return Organization_ID_DEFAULT
	}
	return *p.ID
}

var Organization_Code_DEFAULT string

func (p *Organization) GetCode() (v string) {
	if !p.IsSetCode() {
		return Organization_Code_DEFAULT
	}
	return *p.Code
}

var Organization_Name_DEFAULT string

func (p *Organization) GetName() (v string) {
	if !p.IsSetName() {
		return Organization_Name_DEFAULT
	}
	return *p.Name
}

var Organization_ParentID_DEFAULT core.UUID

func (p *Organization) GetParentID() (v core.UUID) {
	if !p.IsSetParentID() {
		return Organization_ParentID_DEFAULT
	}
	return *p.ParentID
}

var Organization_FacilityType_DEFAULT string

func (p *Organization) GetFacilityType() (v string) {
	if !p.IsSetFacilityType() {
		return Organization_FacilityType_DEFAULT
	}
	return *p.FacilityType
}

var Organization_AccreditationStatus_DEFAULT string

func (p *Organization) GetAccreditationStatus() (v string) {
	if !p.IsSetAccreditationStatus() {
		return Organization_AccreditationStatus_DEFAULT
	}
	return *p.AccreditationStatus
}

var Organization_Logo_DEFAULT string

func (p *Organization) GetLogo() (v string) {
	if !p.IsSetLogo() {
		return Organization_Logo_DEFAULT
	}
	return *p.Logo
}

var Organization_LogoID_DEFAULT core.UUID

func (p *Organization) GetLogoID() (v core.UUID) {
	if !p.IsSetLogoID() {
		return Organization_LogoID_DEFAULT
	}
	return *p.LogoID
}

var Organization_ProvinceCity_DEFAULT []string

func (p *Organization) GetProvinceCity() (v []string) {
	if !p.IsSetProvinceCity() {
		return Organization_ProvinceCity_DEFAULT
	}
	return p.ProvinceCity
}

var Organization_CreatedAt_DEFAULT core.TimestampMS

func (p *Organization) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return Organization_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var Organization_UpdatedAt_DEFAULT core.TimestampMS

func (p *Organization) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return Organization_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *Organization) SetID(val *core.UUID) {
	p.ID = val
}
func (p *Organization) SetCode(val *string) {
	p.Code = val
}
func (p *Organization) SetName(val *string) {
	p.Name = val
}
func (p *Organization) SetParentID(val *core.UUID) {
	p.ParentID = val
}
func (p *Organization) SetFacilityType(val *string) {
	p.FacilityType = val
}
func (p *Organization) SetAccreditationStatus(val *string) {
	p.AccreditationStatus = val
}
func (p *Organization) SetLogo(val *string) {
	p.Logo = val
}
func (p *Organization) SetLogoID(val *core.UUID) {
	p.LogoID = val
}
func (p *Organization) SetProvinceCity(val []string) {
	p.ProvinceCity = val
}
func (p *Organization) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *Organization) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *Organization) IsSetID() bool {
	return p.ID != nil
}

func (p *Organization) IsSetCode() bool {
	return p.Code != nil
}

func (p *Organization) IsSetName() bool {
	return p.Name != nil
}

func (p *Organization) IsSetParentID() bool {
	return p.ParentID != nil
}

func (p *Organization) IsSetFacilityType() bool {
	return p.FacilityType != nil
}

func (p *Organization) IsSetAccreditationStatus() bool {
	return p.AccreditationStatus != nil
}

func (p *Organization) IsSetLogo() bool {
	return p.Logo != nil
}

func (p *Organization) IsSetLogoID() bool {
	return p.LogoID != nil
}

func (p *Organization) IsSetProvinceCity() bool {
	return p.ProvinceCity != nil
}

func (p *Organization) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Organization) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Organization) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Organization(%+v)", *p)
}

var fieldIDToName_Organization = map[int16]string{
	1:  "ID",
	2:  "code",
	3:  "name",
	4:  "parentID",
	5:  "facilityType",
	6:  "accreditationStatus",
	7:  "logo",
	15: "logoID",
	8:  "provinceCity",
	9:  "createdAt",
	10: "updatedAt",
}

type Department struct {
	ID                 *core.UUID        `thrift:"ID,1,optional" frugal:"1,optional,string" json:"ID,omitempty"`
	Code               *string           `thrift:"code,2,optional" frugal:"2,optional,string" json:"code,omitempty"`
	Name               *string           `thrift:"name,3,optional" frugal:"3,optional,string" json:"name,omitempty"`
	OrganizationID     *core.UUID        `thrift:"organizationID,4,optional" frugal:"4,optional,string" json:"organizationID,omitempty"`
	DepartmentType     *string           `thrift:"departmentType,5,optional" frugal:"5,optional,string" json:"departmentType,omitempty"`
	AvailableEquipment []core.UUID       `thrift:"availableEquipment,6,optional" frugal:"6,optional,list<string>" json:"availableEquipment,omitempty"`
	CreatedAt          *core.TimestampMS `thrift:"createdAt,7,optional" frugal:"7,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt          *core.TimestampMS `thrift:"updatedAt,8,optional" frugal:"8,optional,i64" json:"updatedAt,omitempty"`
}

func NewDepartment() *Department {
	return &Department{}
}

func (p *Department) InitDefault() {
}

var Department_ID_DEFAULT core.UUID

func (p *Department) GetID() (v core.UUID) {
	if !p.IsSetID() {
		return Department_ID_DEFAULT
	}
	return *p.ID
}

var Department_Code_DEFAULT string

func (p *Department) GetCode() (v string) {
	if !p.IsSetCode() {
		return Department_Code_DEFAULT
	}
	return *p.Code
}

var Department_Name_DEFAULT string

func (p *Department) GetName() (v string) {
	if !p.IsSetName() {
		return Department_Name_DEFAULT
	}
	return *p.Name
}

var Department_OrganizationID_DEFAULT core.UUID

func (p *Department) GetOrganizationID() (v core.UUID) {
	if !p.IsSetOrganizationID() {
		return Department_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var Department_DepartmentType_DEFAULT string

func (p *Department) GetDepartmentType() (v string) {
	if !p.IsSetDepartmentType() {
		return Department_DepartmentType_DEFAULT
	}
	return *p.DepartmentType
}

var Department_AvailableEquipment_DEFAULT []core.UUID

func (p *Department) GetAvailableEquipment() (v []core.UUID) {
	if !p.IsSetAvailableEquipment() {
		return Department_AvailableEquipment_DEFAULT
	}
	return p.AvailableEquipment
}

var Department_CreatedAt_DEFAULT core.TimestampMS

func (p *Department) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return Department_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var Department_UpdatedAt_DEFAULT core.TimestampMS

func (p *Department) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return Department_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *Department) SetID(val *core.UUID) {
	p.ID = val
}
func (p *Department) SetCode(val *string) {
	p.Code = val
}
func (p *Department) SetName(val *string) {
	p.Name = val
}
func (p *Department) SetOrganizationID(val *core.UUID) {
	p.OrganizationID = val
}
func (p *Department) SetDepartmentType(val *string) {
	p.DepartmentType = val
}
func (p *Department) SetAvailableEquipment(val []core.UUID) {
	p.AvailableEquipment = val
}
func (p *Department) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *Department) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *Department) IsSetID() bool {
	return p.ID != nil
}

func (p *Department) IsSetCode() bool {
	return p.Code != nil
}

func (p *Department) IsSetName() bool {
	return p.Name != nil
}

func (p *Department) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *Department) IsSetDepartmentType() bool {
	return p.DepartmentType != nil
}

func (p *Department) IsSetAvailableEquipment() bool {
	return p.AvailableEquipment != nil
}

func (p *Department) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *Department) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *Department) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Department(%+v)", *p)
}

var fieldIDToName_Department = map[int16]string{
	1: "ID",
	2: "code",
	3: "name",
	4: "organizationID",
	5: "departmentType",
	6: "availableEquipment",
	7: "createdAt",
	8: "updatedAt",
}

type OrganizationLogo struct {
	ID                  *core.UUID              `thrift:"ID,1,optional" frugal:"1,optional,string" json:"ID,omitempty"`
	FileID              *string                 `thrift:"fileID,2,optional" frugal:"2,optional,string" json:"fileID,omitempty"`
	Status              *OrganizationLogoStatus `thrift:"status,3,optional" frugal:"3,optional,OrganizationLogoStatus" json:"status,omitempty"`
	BoundOrganizationID *core.UUID              `thrift:"boundOrganizationID,4,optional" frugal:"4,optional,string" json:"boundOrganizationID,omitempty"`
	FileName            *string                 `thrift:"fileName,5,optional" frugal:"5,optional,string" json:"fileName,omitempty"`
	FileSize            *int64                  `thrift:"fileSize,6,optional" frugal:"6,optional,i64" json:"fileSize,omitempty"`
	MimeType            *string                 `thrift:"mimeType,7,optional" frugal:"7,optional,string" json:"mimeType,omitempty"`
	DownloadUrl         *string                 `thrift:"downloadUrl,8,optional" frugal:"8,optional,string" json:"downloadUrl,omitempty"`
	ExpiresAt           *core.TimestampMS       `thrift:"expiresAt,9,optional" frugal:"9,optional,i64" json:"expiresAt,omitempty"`
	UploadedBy          *core.UUID              `thrift:"uploadedBy,10,optional" frugal:"10,optional,string" json:"uploadedBy,omitempty"`
	CreatedAt           *core.TimestampMS       `thrift:"createdAt,11,optional" frugal:"11,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt           *core.TimestampMS       `thrift:"updatedAt,12,optional" frugal:"12,optional,i64" json:"updatedAt,omitempty"`
}

func NewOrganizationLogo() *OrganizationLogo {
	return &OrganizationLogo{}
}

func (p *OrganizationLogo) InitDefault() {
}

var OrganizationLogo_ID_DEFAULT core.UUID

func (p *OrganizationLogo) GetID() (v core.UUID) {
	if !p.IsSetID() {
		return OrganizationLogo_ID_DEFAULT
	}
	return *p.ID
}

var OrganizationLogo_FileID_DEFAULT string

func (p *OrganizationLogo) GetFileID() (v string) {
	if !p.IsSetFileID() {
		return OrganizationLogo_FileID_DEFAULT
	}
	return *p.FileID
}

var OrganizationLogo_Status_DEFAULT OrganizationLogoStatus

func (p *OrganizationLogo) GetStatus() (v OrganizationLogoStatus) {
	if !p.IsSetStatus() {
		return OrganizationLogo_Status_DEFAULT
	}
	return *p.Status
}

var OrganizationLogo_BoundOrganizationID_DEFAULT core.UUID

func (p *OrganizationLogo) GetBoundOrganizationID() (v core.UUID) {
	if !p.IsSetBoundOrganizationID() {
		return OrganizationLogo_BoundOrganizationID_DEFAULT
	}
	return *p.BoundOrganizationID
}

var OrganizationLogo_FileName_DEFAULT string

func (p *OrganizationLogo) GetFileName() (v string) {
	if !p.IsSetFileName() {
		return OrganizationLogo_FileName_DEFAULT
	}
	return *p.FileName
}

var OrganizationLogo_FileSize_DEFAULT int64

func (p *OrganizationLogo) GetFileSize() (v int64) {
	if !p.IsSetFileSize() {
		return OrganizationLogo_FileSize_DEFAULT
	}
	return *p.FileSize
}

var OrganizationLogo_MimeType_DEFAULT string

func (p *OrganizationLogo) GetMimeType() (v string) {
	if !p.IsSetMimeType() {
		return OrganizationLogo_MimeType_DEFAULT
	}
	return *p.MimeType
}

var OrganizationLogo_DownloadUrl_DEFAULT string

func (p *OrganizationLogo) GetDownloadUrl() (v string) {
	if !p.IsSetDownloadUrl() {
		return OrganizationLogo_DownloadUrl_DEFAULT
	}
	return *p.DownloadUrl
}

var OrganizationLogo_ExpiresAt_DEFAULT core.TimestampMS

func (p *OrganizationLogo) GetExpiresAt() (v core.TimestampMS) {
	if !p.IsSetExpiresAt() {
		return OrganizationLogo_ExpiresAt_DEFAULT
	}
	return *p.ExpiresAt
}

var OrganizationLogo_UploadedBy_DEFAULT core.UUID

func (p *OrganizationLogo) GetUploadedBy() (v core.UUID) {
	if !p.IsSetUploadedBy() {
		return OrganizationLogo_UploadedBy_DEFAULT
	}
	return *p.UploadedBy
}

var OrganizationLogo_CreatedAt_DEFAULT core.TimestampMS

func (p *OrganizationLogo) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return OrganizationLogo_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var OrganizationLogo_UpdatedAt_DEFAULT core.TimestampMS

func (p *OrganizationLogo) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return OrganizationLogo_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *OrganizationLogo) SetID(val *core.UUID) {
	p.ID = val
}
func (p *OrganizationLogo) SetFileID(val *string) {
	p.FileID = val
}
func (p *OrganizationLogo) SetStatus(val *OrganizationLogoStatus) {
	p.Status = val
}
func (p *OrganizationLogo) SetBoundOrganizationID(val *core.UUID) {
	p.BoundOrganizationID = val
}
func (p *OrganizationLogo) SetFileName(val *string) {
	p.FileName = val
}
func (p *OrganizationLogo) SetFileSize(val *int64) {
	p.FileSize = val
}
func (p *OrganizationLogo) SetMimeType(val *string) {
	p.MimeType = val
}
func (p *OrganizationLogo) SetDownloadUrl(val *string) {
	p.DownloadUrl = val
}
func (p *OrganizationLogo) SetExpiresAt(val *core.TimestampMS) {
	p.ExpiresAt = val
}
func (p *OrganizationLogo) SetUploadedBy(val *core.UUID) {
	p.UploadedBy = val
}
func (p *OrganizationLogo) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *OrganizationLogo) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *OrganizationLogo) IsSetID() bool {
	return p.ID != nil
}

func (p *OrganizationLogo) IsSetFileID() bool {
	return p.FileID != nil
}

func (p *OrganizationLogo) IsSetStatus() bool {
	return p.Status != nil
}

func (p *OrganizationLogo) IsSetBoundOrganizationID() bool {
	return p.BoundOrganizationID != nil
}

func (p *OrganizationLogo) IsSetFileName() bool {
	return p.FileName != nil
}

func (p *OrganizationLogo) IsSetFileSize() bool {
	return p.FileSize != nil
}

func (p *OrganizationLogo) IsSetMimeType() bool {
	return p.MimeType != nil
}

func (p *OrganizationLogo) IsSetDownloadUrl() bool {
	return p.DownloadUrl != nil
}

func (p *OrganizationLogo) IsSetExpiresAt() bool {
	return p.ExpiresAt != nil
}

func (p *OrganizationLogo) IsSetUploadedBy() bool {
	return p.UploadedBy != nil
}

func (p *OrganizationLogo) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *OrganizationLogo) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *OrganizationLogo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrganizationLogo(%+v)", *p)
}

var fieldIDToName_OrganizationLogo = map[int16]string{
	1:  "ID",
	2:  "fileID",
	3:  "status",
	4:  "boundOrganizationID",
	5:  "fileName",
	6:  "fileSize",
	7:  "mimeType",
	8:  "downloadUrl",
	9:  "expiresAt",
	10: "uploadedBy",
	11: "createdAt",
	12: "updatedAt",
}

type Permission struct {
	Resource    *string `thrift:"resource,1,optional" frugal:"1,optional,string" json:"resource,omitempty"`
	Action      *string `thrift:"action,2,optional" frugal:"2,optional,string" json:"action,omitempty"`
	Description *string `thrift:"description,3,optional" frugal:"3,optional,string" json:"description,omitempty"`
}

func NewPermission() *Permission {
	return &Permission{}
}

func (p *Permission) InitDefault() {
}

var Permission_Resource_DEFAULT string

func (p *Permission) GetResource() (v string) {
	if !p.IsSetResource() {
		return Permission_Resource_DEFAULT
	}
	return *p.Resource
}

var Permission_Action_DEFAULT string

func (p *Permission) GetAction() (v string) {
	if !p.IsSetAction() {
		return Permission_Action_DEFAULT
	}
	return *p.Action
}

var Permission_Description_DEFAULT string

func (p *Permission) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return Permission_Description_DEFAULT
	}
	return *p.Description
}
func (p *Permission) SetResource(val *string) {
	p.Resource = val
}
func (p *Permission) SetAction(val *string) {
	p.Action = val
}
func (p *Permission) SetDescription(val *string) {
	p.Description = val
}

func (p *Permission) IsSetResource() bool {
	return p.Resource != nil
}

func (p *Permission) IsSetAction() bool {
	return p.Action != nil
}

func (p *Permission) IsSetDescription() bool {
	return p.Description != nil
}

func (p *Permission) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Permission(%+v)", *p)
}

var fieldIDToName_Permission = map[int16]string{
	1: "resource",
	2: "action",
	3: "description",
}

type RoleDefinition struct {
	Id           *core.UUID        `thrift:"id,1,optional" frugal:"1,optional,string" json:"id,omitempty"`
	Name         *string           `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Description  *string           `thrift:"description,3,optional" frugal:"3,optional,string" json:"description,omitempty"`
	Status       *core.RoleStatus  `thrift:"status,5,optional" frugal:"5,optional,RoleStatus" json:"status,omitempty"`
	Permissions  []*Permission     `thrift:"permissions,6,optional" frugal:"6,optional,list<Permission>" json:"permissions,omitempty"`
	IsSystemRole bool              `thrift:"isSystemRole,7,optional" frugal:"7,optional,bool" json:"isSystemRole,omitempty"`
	CreatedBy    *core.UUID        `thrift:"createdBy,8,optional" frugal:"8,optional,string" json:"createdBy,omitempty"`
	UpdatedBy    *core.UUID        `thrift:"updatedBy,9,optional" frugal:"9,optional,string" json:"updatedBy,omitempty"`
	CreatedAt    *core.TimestampMS `thrift:"createdAt,10,optional" frugal:"10,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt    *core.TimestampMS `thrift:"updatedAt,11,optional" frugal:"11,optional,i64" json:"updatedAt,omitempty"`
	UserCount    *int64            `thrift:"userCount,12,optional" frugal:"12,optional,i64" json:"userCount,omitempty"`
}

func NewRoleDefinition() *RoleDefinition {
	return &RoleDefinition{
		IsSystemRole: false,
	}
}

func (p *RoleDefinition) InitDefault() {
	p.IsSystemRole = false
}

var RoleDefinition_Id_DEFAULT core.UUID

func (p *RoleDefinition) GetId() (v core.UUID) {
	if !p.IsSetId() {
		return RoleDefinition_Id_DEFAULT
	}
	return *p.Id
}

var RoleDefinition_Name_DEFAULT string

func (p *RoleDefinition) GetName() (v string) {
	if !p.IsSetName() {
		return RoleDefinition_Name_DEFAULT
	}
	return *p.Name
}

var RoleDefinition_Description_DEFAULT string

func (p *RoleDefinition) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return RoleDefinition_Description_DEFAULT
	}
	return *p.Description
}

var RoleDefinition_Status_DEFAULT core.RoleStatus

func (p *RoleDefinition) GetStatus() (v core.RoleStatus) {
	if !p.IsSetStatus() {
		return RoleDefinition_Status_DEFAULT
	}
	return *p.Status
}

var RoleDefinition_Permissions_DEFAULT []*Permission

func (p *RoleDefinition) GetPermissions() (v []*Permission) {
	if !p.IsSetPermissions() {
		return RoleDefinition_Permissions_DEFAULT
	}
	return p.Permissions
}

var RoleDefinition_IsSystemRole_DEFAULT bool = false

func (p *RoleDefinition) GetIsSystemRole() (v bool) {
	if !p.IsSetIsSystemRole() {
		return RoleDefinition_IsSystemRole_DEFAULT
	}
	return p.IsSystemRole
}

var RoleDefinition_CreatedBy_DEFAULT core.UUID

func (p *RoleDefinition) GetCreatedBy() (v core.UUID) {
	if !p.IsSetCreatedBy() {
		return RoleDefinition_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var RoleDefinition_UpdatedBy_DEFAULT core.UUID

func (p *RoleDefinition) GetUpdatedBy() (v core.UUID) {
	if !p.IsSetUpdatedBy() {
		return RoleDefinition_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var RoleDefinition_CreatedAt_DEFAULT core.TimestampMS

func (p *RoleDefinition) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return RoleDefinition_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var RoleDefinition_UpdatedAt_DEFAULT core.TimestampMS

func (p *RoleDefinition) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return RoleDefinition_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}

var RoleDefinition_UserCount_DEFAULT int64

func (p *RoleDefinition) GetUserCount() (v int64) {
	if !p.IsSetUserCount() {
		return RoleDefinition_UserCount_DEFAULT
	}
	return *p.UserCount
}
func (p *RoleDefinition) SetId(val *core.UUID) {
	p.Id = val
}
func (p *RoleDefinition) SetName(val *string) {
	p.Name = val
}
func (p *RoleDefinition) SetDescription(val *string) {
	p.Description = val
}
func (p *RoleDefinition) SetStatus(val *core.RoleStatus) {
	p.Status = val
}
func (p *RoleDefinition) SetPermissions(val []*Permission) {
	p.Permissions = val
}
func (p *RoleDefinition) SetIsSystemRole(val bool) {
	p.IsSystemRole = val
}
func (p *RoleDefinition) SetCreatedBy(val *core.UUID) {
	p.CreatedBy = val
}
func (p *RoleDefinition) SetUpdatedBy(val *core.UUID) {
	p.UpdatedBy = val
}
func (p *RoleDefinition) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *RoleDefinition) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}
func (p *RoleDefinition) SetUserCount(val *int64) {
	p.UserCount = val
}

func (p *RoleDefinition) IsSetId() bool {
	return p.Id != nil
}

func (p *RoleDefinition) IsSetName() bool {
	return p.Name != nil
}

func (p *RoleDefinition) IsSetDescription() bool {
	return p.Description != nil
}

func (p *RoleDefinition) IsSetStatus() bool {
	return p.Status != nil
}

func (p *RoleDefinition) IsSetPermissions() bool {
	return p.Permissions != nil
}

func (p *RoleDefinition) IsSetIsSystemRole() bool {
	return p.IsSystemRole != RoleDefinition_IsSystemRole_DEFAULT
}

func (p *RoleDefinition) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *RoleDefinition) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *RoleDefinition) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *RoleDefinition) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *RoleDefinition) IsSetUserCount() bool {
	return p.UserCount != nil
}

func (p *RoleDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RoleDefinition(%+v)", *p)
}

var fieldIDToName_RoleDefinition = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "description",
	5:  "status",
	6:  "permissions",
	7:  "isSystemRole",
	8:  "createdBy",
	9:  "updatedBy",
	10: "createdAt",
	11: "updatedAt",
	12: "userCount",
}

type UserRoleAssignment struct {
	Id        *core.UUID        `thrift:"id,1,optional" frugal:"1,optional,string" json:"id,omitempty"`
	UserID    *core.UUID        `thrift:"userID,2,optional" frugal:"2,optional,string" json:"userID,omitempty"`
	RoleID    *core.UUID        `thrift:"roleID,3,optional" frugal:"3,optional,string" json:"roleID,omitempty"`
	CreatedBy *core.UUID        `thrift:"createdBy,11,optional" frugal:"11,optional,string" json:"createdBy,omitempty"`
	UpdatedBy *core.UUID        `thrift:"updatedBy,12,optional" frugal:"12,optional,string" json:"updatedBy,omitempty"`
	CreatedAt *core.TimestampMS `thrift:"createdAt,13,optional" frugal:"13,optional,i64" json:"createdAt,omitempty"`
	UpdatedAt *core.TimestampMS `thrift:"updatedAt,14,optional" frugal:"14,optional,i64" json:"updatedAt,omitempty"`
}

func NewUserRoleAssignment() *UserRoleAssignment {
	return &UserRoleAssignment{}
}

func (p *UserRoleAssignment) InitDefault() {
}

var UserRoleAssignment_Id_DEFAULT core.UUID

func (p *UserRoleAssignment) GetId() (v core.UUID) {
	if !p.IsSetId() {
		return UserRoleAssignment_Id_DEFAULT
	}
	return *p.Id
}

var UserRoleAssignment_UserID_DEFAULT core.UUID

func (p *UserRoleAssignment) GetUserID() (v core.UUID) {
	if !p.IsSetUserID() {
		return UserRoleAssignment_UserID_DEFAULT
	}
	return *p.UserID
}

var UserRoleAssignment_RoleID_DEFAULT core.UUID

func (p *UserRoleAssignment) GetRoleID() (v core.UUID) {
	if !p.IsSetRoleID() {
		return UserRoleAssignment_RoleID_DEFAULT
	}
	return *p.RoleID
}

var UserRoleAssignment_CreatedBy_DEFAULT core.UUID

func (p *UserRoleAssignment) GetCreatedBy() (v core.UUID) {
	if !p.IsSetCreatedBy() {
		return UserRoleAssignment_CreatedBy_DEFAULT
	}
	return *p.CreatedBy
}

var UserRoleAssignment_UpdatedBy_DEFAULT core.UUID

func (p *UserRoleAssignment) GetUpdatedBy() (v core.UUID) {
	if !p.IsSetUpdatedBy() {
		return UserRoleAssignment_UpdatedBy_DEFAULT
	}
	return *p.UpdatedBy
}

var UserRoleAssignment_CreatedAt_DEFAULT core.TimestampMS

func (p *UserRoleAssignment) GetCreatedAt() (v core.TimestampMS) {
	if !p.IsSetCreatedAt() {
		return UserRoleAssignment_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var UserRoleAssignment_UpdatedAt_DEFAULT core.TimestampMS

func (p *UserRoleAssignment) GetUpdatedAt() (v core.TimestampMS) {
	if !p.IsSetUpdatedAt() {
		return UserRoleAssignment_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *UserRoleAssignment) SetId(val *core.UUID) {
	p.Id = val
}
func (p *UserRoleAssignment) SetUserID(val *core.UUID) {
	p.UserID = val
}
func (p *UserRoleAssignment) SetRoleID(val *core.UUID) {
	p.RoleID = val
}
func (p *UserRoleAssignment) SetCreatedBy(val *core.UUID) {
	p.CreatedBy = val
}
func (p *UserRoleAssignment) SetUpdatedBy(val *core.UUID) {
	p.UpdatedBy = val
}
func (p *UserRoleAssignment) SetCreatedAt(val *core.TimestampMS) {
	p.CreatedAt = val
}
func (p *UserRoleAssignment) SetUpdatedAt(val *core.TimestampMS) {
	p.UpdatedAt = val
}

func (p *UserRoleAssignment) IsSetId() bool {
	return p.Id != nil
}

func (p *UserRoleAssignment) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *UserRoleAssignment) IsSetRoleID() bool {
	return p.RoleID != nil
}

func (p *UserRoleAssignment) IsSetCreatedBy() bool {
	return p.CreatedBy != nil
}

func (p *UserRoleAssignment) IsSetUpdatedBy() bool {
	return p.UpdatedBy != nil
}

func (p *UserRoleAssignment) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *UserRoleAssignment) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *UserRoleAssignment) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserRoleAssignment(%+v)", *p)
}

var fieldIDToName_UserRoleAssignment = map[int16]string{
	1:  "id",
	2:  "userID",
	3:  "roleID",
	11: "createdBy",
	12: "updatedBy",
	13: "createdAt",
	14: "updatedAt",
}

type MenuNode struct {
	Name            *string     `thrift:"name,1,optional" frugal:"1,optional,string" json:"name,omitempty"`
	Id              *string     `thrift:"id,2,optional" frugal:"2,optional,string" json:"id,omitempty"`
	Path            *string     `thrift:"path,3,optional" frugal:"3,optional,string" json:"path,omitempty"`
	Icon            *string     `thrift:"icon,4,optional" frugal:"4,optional,string" json:"icon,omitempty"`
	Component       *string     `thrift:"component,5,optional" frugal:"5,optional,string" json:"component,omitempty"`
	Children        []*MenuNode `thrift:"children,6,optional" frugal:"6,optional,list<MenuNode>" json:"children,omitempty"`
	HasPermission   *bool       `thrift:"hasPermission,7,optional" frugal:"7,optional,bool" json:"hasPermission,omitempty"`
	PermissionLevel *string     `thrift:"permissionLevel,8,optional" frugal:"8,optional,string" json:"permissionLevel,omitempty"`
}

func NewMenuNode() *MenuNode {
	return &MenuNode{}
}

func (p *MenuNode) InitDefault() {
}

var MenuNode_Name_DEFAULT string

func (p *MenuNode) GetName() (v string) {
	if !p.IsSetName() {
		return MenuNode_Name_DEFAULT
	}
	return *p.Name
}

var MenuNode_Id_DEFAULT string

func (p *MenuNode) GetId() (v string) {
	if !p.IsSetId() {
		return MenuNode_Id_DEFAULT
	}
	return *p.Id
}

var MenuNode_Path_DEFAULT string

func (p *MenuNode) GetPath() (v string) {
	if !p.IsSetPath() {
		return MenuNode_Path_DEFAULT
	}
	return *p.Path
}

var MenuNode_Icon_DEFAULT string

func (p *MenuNode) GetIcon() (v string) {
	if !p.IsSetIcon() {
		return MenuNode_Icon_DEFAULT
	}
	return *p.Icon
}

var MenuNode_Component_DEFAULT string

func (p *MenuNode) GetComponent() (v string) {
	if !p.IsSetComponent() {
		return MenuNode_Component_DEFAULT
	}
	return *p.Component
}

var MenuNode_Children_DEFAULT []*MenuNode

func (p *MenuNode) GetChildren() (v []*MenuNode) {
	if !p.IsSetChildren() {
		return MenuNode_Children_DEFAULT
	}
	return p.Children
}

var MenuNode_HasPermission_DEFAULT bool

func (p *MenuNode) GetHasPermission() (v bool) {
	if !p.IsSetHasPermission() {
		return MenuNode_HasPermission_DEFAULT
	}
	return *p.HasPermission
}

var MenuNode_PermissionLevel_DEFAULT string

func (p *MenuNode) GetPermissionLevel() (v string) {
	if !p.IsSetPermissionLevel() {
		return MenuNode_PermissionLevel_DEFAULT
	}
	return *p.PermissionLevel
}
func (p *MenuNode) SetName(val *string) {
	p.Name = val
}
func (p *MenuNode) SetId(val *string) {
	p.Id = val
}
func (p *MenuNode) SetPath(val *string) {
	p.Path = val
}
func (p *MenuNode) SetIcon(val *string) {
	p.Icon = val
}
func (p *MenuNode) SetComponent(val *string) {
	p.Component = val
}
func (p *MenuNode) SetChildren(val []*MenuNode) {
	p.Children = val
}
func (p *MenuNode) SetHasPermission(val *bool) {
	p.HasPermission = val
}
func (p *MenuNode) SetPermissionLevel(val *string) {
	p.PermissionLevel = val
}

func (p *MenuNode) IsSetName() bool {
	return p.Name != nil
}

func (p *MenuNode) IsSetId() bool {
	return p.Id != nil
}

func (p *MenuNode) IsSetPath() bool {
	return p.Path != nil
}

func (p *MenuNode) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *MenuNode) IsSetComponent() bool {
	return p.Component != nil
}

func (p *MenuNode) IsSetChildren() bool {
	return p.Children != nil
}

func (p *MenuNode) IsSetHasPermission() bool {
	return p.HasPermission != nil
}

func (p *MenuNode) IsSetPermissionLevel() bool {
	return p.PermissionLevel != nil
}

func (p *MenuNode) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MenuNode(%+v)", *p)
}

var fieldIDToName_MenuNode = map[int16]string{
	1: "name",
	2: "id",
	3: "path",
	4: "icon",
	5: "component",
	6: "children",
	7: "hasPermission",
	8: "permissionLevel",
}
