// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package core

import (
	"fmt"
)

type ULID = string

type UUID = string

type TimestampMS = int64

type URL = string

type IPAddress = string

type RequestContext struct {
	RequestID      *string           `thrift:"requestID,1,optional" frugal:"1,optional,string" json:"requestID,omitempty"`
	TraceID        *string           `thrift:"traceID,2,optional" frugal:"2,optional,string" json:"traceID,omitempty"`
	RequestTime    *TimestampMS      `thrift:"requestTime,3,optional" frugal:"3,optional,i64" json:"requestTime,omitempty"`
	ClientIP       *string           `thrift:"clientIP,4,optional" frugal:"4,optional,string" json:"clientIP,omitempty"`
	UserAgent      *string           `thrift:"userAgent,5,optional" frugal:"5,optional,string" json:"userAgent,omitempty"`
	UserID         *string           `thrift:"userID,6,optional" frugal:"6,optional,string" json:"userID,omitempty"`
	OrganizationID *string           `thrift:"organizationID,7,optional" frugal:"7,optional,string" json:"organizationID,omitempty"`
	TenantID       *string           `thrift:"tenantID,8,optional" frugal:"8,optional,string" json:"tenantID,omitempty"`
	Source         *string           `thrift:"source,9,optional" frugal:"9,optional,string" json:"source,omitempty"`
	Locale         *string           `thrift:"locale,10,optional" frugal:"10,optional,string" json:"locale,omitempty"`
	Metadata       map[string]string `thrift:"metadata,11,optional" frugal:"11,optional,map<string:string>" json:"metadata,omitempty"`
}

func NewRequestContext() *RequestContext {
	return &RequestContext{}
}

func (p *RequestContext) InitDefault() {
}

var RequestContext_RequestID_DEFAULT string

func (p *RequestContext) GetRequestID() (v string) {
	if !p.IsSetRequestID() {
		return RequestContext_RequestID_DEFAULT
	}
	return *p.RequestID
}

var RequestContext_TraceID_DEFAULT string

func (p *RequestContext) GetTraceID() (v string) {
	if !p.IsSetTraceID() {
		return RequestContext_TraceID_DEFAULT
	}
	return *p.TraceID
}

var RequestContext_RequestTime_DEFAULT TimestampMS

func (p *RequestContext) GetRequestTime() (v TimestampMS) {
	if !p.IsSetRequestTime() {
		return RequestContext_RequestTime_DEFAULT
	}
	return *p.RequestTime
}

var RequestContext_ClientIP_DEFAULT string

func (p *RequestContext) GetClientIP() (v string) {
	if !p.IsSetClientIP() {
		return RequestContext_ClientIP_DEFAULT
	}
	return *p.ClientIP
}

var RequestContext_UserAgent_DEFAULT string

func (p *RequestContext) GetUserAgent() (v string) {
	if !p.IsSetUserAgent() {
		return RequestContext_UserAgent_DEFAULT
	}
	return *p.UserAgent
}

var RequestContext_UserID_DEFAULT string

func (p *RequestContext) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return RequestContext_UserID_DEFAULT
	}
	return *p.UserID
}

var RequestContext_OrganizationID_DEFAULT string

func (p *RequestContext) GetOrganizationID() (v string) {
	if !p.IsSetOrganizationID() {
		return RequestContext_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var RequestContext_TenantID_DEFAULT string

func (p *RequestContext) GetTenantID() (v string) {
	if !p.IsSetTenantID() {
		return RequestContext_TenantID_DEFAULT
	}
	return *p.TenantID
}

var RequestContext_Source_DEFAULT string

func (p *RequestContext) GetSource() (v string) {
	if !p.IsSetSource() {
		return RequestContext_Source_DEFAULT
	}
	return *p.Source
}

var RequestContext_Locale_DEFAULT string

func (p *RequestContext) GetLocale() (v string) {
	if !p.IsSetLocale() {
		return RequestContext_Locale_DEFAULT
	}
	return *p.Locale
}

var RequestContext_Metadata_DEFAULT map[string]string

func (p *RequestContext) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return RequestContext_Metadata_DEFAULT
	}
	return p.Metadata
}
func (p *RequestContext) SetRequestID(val *string) {
	p.RequestID = val
}
func (p *RequestContext) SetTraceID(val *string) {
	p.TraceID = val
}
func (p *RequestContext) SetRequestTime(val *TimestampMS) {
	p.RequestTime = val
}
func (p *RequestContext) SetClientIP(val *string) {
	p.ClientIP = val
}
func (p *RequestContext) SetUserAgent(val *string) {
	p.UserAgent = val
}
func (p *RequestContext) SetUserID(val *string) {
	p.UserID = val
}
func (p *RequestContext) SetOrganizationID(val *string) {
	p.OrganizationID = val
}
func (p *RequestContext) SetTenantID(val *string) {
	p.TenantID = val
}
func (p *RequestContext) SetSource(val *string) {
	p.Source = val
}
func (p *RequestContext) SetLocale(val *string) {
	p.Locale = val
}
func (p *RequestContext) SetMetadata(val map[string]string) {
	p.Metadata = val
}

func (p *RequestContext) IsSetRequestID() bool {
	return p.RequestID != nil
}

func (p *RequestContext) IsSetTraceID() bool {
	return p.TraceID != nil
}

func (p *RequestContext) IsSetRequestTime() bool {
	return p.RequestTime != nil
}

func (p *RequestContext) IsSetClientIP() bool {
	return p.ClientIP != nil
}

func (p *RequestContext) IsSetUserAgent() bool {
	return p.UserAgent != nil
}

func (p *RequestContext) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *RequestContext) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *RequestContext) IsSetTenantID() bool {
	return p.TenantID != nil
}

func (p *RequestContext) IsSetSource() bool {
	return p.Source != nil
}

func (p *RequestContext) IsSetLocale() bool {
	return p.Locale != nil
}

func (p *RequestContext) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *RequestContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestContext(%+v)", *p)
}

var fieldIDToName_RequestContext = map[int16]string{
	1:  "requestID",
	2:  "traceID",
	3:  "requestTime",
	4:  "clientIP",
	5:  "userAgent",
	6:  "userID",
	7:  "organizationID",
	8:  "tenantID",
	9:  "source",
	10: "locale",
	11: "metadata",
}
