// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package core

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type UserStatus int64

const (
	UserStatus_ACTIVE    UserStatus = 1
	UserStatus_INACTIVE  UserStatus = 2
	UserStatus_SUSPENDED UserStatus = 3
	UserStatus_LOCKED    UserStatus = 4
)

func (p UserStatus) String() string {
	switch p {
	case UserStatus_ACTIVE:
		return "ACTIVE"
	case UserStatus_INACTIVE:
		return "INACTIVE"
	case UserStatus_SUSPENDED:
		return "SUSPENDED"
	case UserStatus_LOCKED:
		return "LOCKED"
	}
	return "<UNSET>"
}

func UserStatusFromString(s string) (UserStatus, error) {
	switch s {
	case "ACTIVE":
		return UserStatus_ACTIVE, nil
	case "INACTIVE":
		return UserStatus_INACTIVE, nil
	case "SUSPENDED":
		return UserStatus_SUSPENDED, nil
	case "LOCKED":
		return UserStatus_LOCKED, nil
	}
	return UserStatus(0), fmt.Errorf("not a valid UserStatus string")
}

func UserStatusPtr(v UserStatus) *UserStatus { return &v }
func (p *UserStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserStatus(result.Int64)
	return
}

func (p *UserStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RoleStatus int64

const (
	RoleStatus_ACTIVE     RoleStatus = 1
	RoleStatus_INACTIVE   RoleStatus = 2
	RoleStatus_DEPRECATED RoleStatus = 3
)

func (p RoleStatus) String() string {
	switch p {
	case RoleStatus_ACTIVE:
		return "ACTIVE"
	case RoleStatus_INACTIVE:
		return "INACTIVE"
	case RoleStatus_DEPRECATED:
		return "DEPRECATED"
	}
	return "<UNSET>"
}

func RoleStatusFromString(s string) (RoleStatus, error) {
	switch s {
	case "ACTIVE":
		return RoleStatus_ACTIVE, nil
	case "INACTIVE":
		return RoleStatus_INACTIVE, nil
	case "DEPRECATED":
		return RoleStatus_DEPRECATED, nil
	}
	return RoleStatus(0), fmt.Errorf("not a valid RoleStatus string")
}

func RoleStatusPtr(v RoleStatus) *RoleStatus { return &v }
func (p *RoleStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RoleStatus(result.Int64)
	return
}

func (p *RoleStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Gender int64

const (
	Gender_UNKNOWN Gender = 0
	Gender_MALE    Gender = 1
	Gender_FEMALE  Gender = 2
)

func (p Gender) String() string {
	switch p {
	case Gender_UNKNOWN:
		return "UNKNOWN"
	case Gender_MALE:
		return "MALE"
	case Gender_FEMALE:
		return "FEMALE"
	}
	return "<UNSET>"
}

func GenderFromString(s string) (Gender, error) {
	switch s {
	case "UNKNOWN":
		return Gender_UNKNOWN, nil
	case "MALE":
		return Gender_MALE, nil
	case "FEMALE":
		return Gender_FEMALE, nil
	}
	return Gender(0), fmt.Errorf("not a valid Gender string")
}

func GenderPtr(v Gender) *Gender { return &v }
func (p *Gender) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Gender(result.Int64)
	return
}

func (p *Gender) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
