// Code generated by hertz generator.

package permission

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _permissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listroledefinitionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hasmenupermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrolemenupermissionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrolemenutreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _configurerolemenusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusersbyroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchbinduserstoroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roles0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroledefinitionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateroledefinitionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteroledefinitionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getroledefinitionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listuserroleassignmentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmenutreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadmenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _users0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useridMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusermenutreeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roles1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlastuserroleassignmentMw() []app.HandlerFunc {
	// your code...
	return nil
}
