// Code generated by hertz generator. DO NOT EDIT.

package identity

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	identity "github.com/masonsxu/cloudwego-scaffold/gateway/biz/handler/identity"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_identity := _v1.Group("/identity", _identityMw()...)
				_identity.POST("/departments", append(_createdepartmentMw(), identity.CreateDepartment)...)
				_departments := _identity.Group("/departments", _departmentsMw()...)
				_departments.DELETE("/:departmentID", append(_deletedepartmentMw(), identity.DeleteDepartment)...)
				_departments.GET("/:departmentID", append(_getdepartmentMw(), identity.GetDepartment)...)
				_departments.PUT("/:departmentID", append(_updatedepartmentMw(), identity.UpdateDepartment)...)
				_identity.GET("/organizations", append(_listorganizationsMw(), identity.ListOrganizations)...)
				_organizations := _identity.Group("/organizations", _organizationsMw()...)
				{
					_organizationid := _organizations.Group("/:organizationID", _organizationidMw()...)
					_organizationid.GET("/departments", append(_getorganizationdepartmentsMw(), identity.GetOrganizationDepartments)...)
					_organizationid.PUT("/logo", append(_bindlogotoorganizationMw(), identity.BindLogoToOrganization)...)
				}
				_identity.POST("/organizations", append(_createorganizationMw(), identity.CreateOrganization)...)
				_organizations0 := _identity.Group("/organizations", _organizations0Mw()...)
				_organizations0.DELETE("/:organizationID", append(_deleteorganizationMw(), identity.DeleteOrganization)...)
				_organizations0.GET("/:organizationID", append(_getorganizationMw(), identity.GetOrganization)...)
				_organizations0.PUT("/:organizationID", append(_updateorganizationMw(), identity.UpdateOrganization)...)
				_identity.GET("/users", append(_listusersMw(), identity.ListUsers)...)
				_users := _identity.Group("/users", _usersMw()...)
				_users.GET("/search", append(_searchusersMw(), identity.SearchUsers)...)
				{
					_userid := _users.Group("/:userID", _useridMw()...)
					_userid.GET("/memberships", append(_getusermembershipsMw(), identity.GetUserMemberships)...)
					_userid.GET("/primary-membership", append(_getprimarymembershipMw(), identity.GetPrimaryMembership)...)
					_userid.PUT("/status", append(_changeuserstatusMw(), identity.ChangeUserStatus)...)
					_userid.PUT("/unlock", append(_unlockuserMw(), identity.UnlockUser)...)
				}
				_identity.POST("/users", append(_createuserMw(), identity.CreateUser)...)
				_users0 := _identity.Group("/users", _users0Mw()...)
				_users0.GET("/me", append(_getmeMw(), identity.GetMe)...)
				_users0.PUT("/me", append(_updatemeMw(), identity.UpdateMe)...)
				_users0.DELETE("/:userID", append(_deleteuserMw(), identity.DeleteUser)...)
				_users0.GET("/:userID", append(_getuserMw(), identity.GetUser)...)
				_users0.PUT("/:userID", append(_updateuserMw(), identity.UpdateUser)...)
				{
					_auth := _identity.Group("/auth", _authMw()...)
					_auth.POST("/login", append(_loginMw(), identity.Login)...)
					_auth.POST("/logout", append(_logoutMw(), identity.Logout)...)
					_auth.PUT("/password", append(_changepasswordMw(), identity.ChangePassword)...)
					_password := _auth.Group("/password", _passwordMw()...)
					_password.PUT("/force-change", append(_forcepasswordchangeMw(), identity.ForcePasswordChange)...)
					_password.POST("/reset", append(_resetpasswordMw(), identity.ResetPassword)...)
					_auth.POST("/refresh", append(_refreshtokenMw(), identity.RefreshToken)...)
				}
				{
					_organization_logos := _identity.Group("/organization-logos", _organization_logosMw()...)
					_organization_logos.DELETE("/:logoID", append(_deleteorganizationlogoMw(), identity.DeleteOrganizationLogo)...)
					_organization_logos.GET("/:logoID", append(_getorganizationlogoMw(), identity.GetOrganizationLogo)...)
					_organization_logos.POST("/temporary", append(_uploadtemporarylogoMw(), identity.UploadTemporaryLogo)...)
				}
			}
		}
	}
}
