// Code generated by hertz generator.

package identity

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _identityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _departmentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedepartmentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organizationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listorganizationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organizationidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorganizationdepartmentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bindlogotoorganizationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organizations0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createorganizationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteorganizationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorganizationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorganizationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _useridMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getusermembershipsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprimarymembershipMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuserstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _unlockuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _users0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forcepasswordchangeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _resetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _organization_logosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteorganizationlogoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorganizationlogoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadtemporarylogoMw() []app.HandlerFunc {
	// your code...
	return nil
}
