// Code generated by hertz generator.

package identity

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/masonsxu/cloudwego-scaffold/gateway/biz/model/core"
	http_base "github.com/masonsxu/cloudwego-scaffold/gateway/biz/model/http_base"
	identity "github.com/masonsxu/cloudwego-scaffold/gateway/biz/model/identity"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/application/context/auth_context"
	jwtMw "github.com/masonsxu/cloudwego-scaffold/gateway/internal/application/middleware/jwt_middleware"
	identityservice "github.com/masonsxu/cloudwego-scaffold/gateway/internal/domain/service/identity"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/infrastructure/errors"
)

// 全局服务实例（通过Wire注入）
var identityService identityservice.Service

// 全局变量保存JWT中间件实例
// 使用接口类型而不是具体结构体类型，符合依赖倒置原则
var jwtMiddlewareInstance jwtMw.JWTMiddlewareService

// 用于解决 core 包导入但未使用的问题
var _ = core.UserStatus_ACTIVE

// 用于解决 http_base 包导入但未使用的问题
var _ http_base.OperationStatusResponseDTO

// SetIdentityService 设置身份服务实例（由Wire在启动时调用）
func SetIdentityService(service identityservice.Service, middleware jwtMw.JWTMiddlewareService) {
	identityService = service
	jwtMiddlewareInstance = middleware
}

// Login
// @Summary 用户登录
// @Description 验证用户凭据并返回访问令牌和用户信息
// @Tags 认证管理
// @Accept json
// @Produce json
// @Param req body identity.LoginRequestDTO true "请求体"
// @Success 200 {object} identity.LoginResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	// 使用全局JWT中间件实例的登录处理器
	jwtMiddlewareInstance.LoginHandler(ctx, c)
}

// Logout
// @Summary 用户登出
// @Description 注销当前会话并使令牌失效
// @Tags 认证管理
// @Accept json
// @Produce json
// @Param req body identity.LogoutRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	// 使用全局JWT中间件实例的登出处理器
	jwtMiddlewareInstance.LogoutHandler(ctx, c)
}

// ChangePassword
// @Summary 修改密码
// @Description 用户修改自己的密码（需要提供旧密码）
// @Tags 认证管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.ChangePasswordRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/password [PUT]
func ChangePassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ChangePasswordRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 获取当前用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	// 调用业务服务层
	resp, err := identityService.ChangePassword(ctx, &req, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "修改用户密码失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ResetPassword
// @Summary 重置密码
// @Description 管理员重置用户密码（管理员权限）
// @Tags 认证管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param req body identity.ResetPasswordRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/password/reset [POST]
func ResetPassword(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ResetPasswordRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.ResetPassword(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "重置用户密码失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ForcePasswordChange
// @Summary 强制下次登录修改密码
// @Description 管理员标记用户需要在下次登录时强制修改密码
// @Tags 认证管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.ForcePasswordChangeRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/password/force-change [PUT]
func ForcePasswordChange(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ForcePasswordChangeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.ForcePasswordChange(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "强制修改用户密码失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// RefreshToken
// @Summary 刷新访问令牌
// @Description 使用刷新令牌获取新的访问令牌
// @Tags 认证管理
// @Accept json
// @Produce json
// @Param req body identity.RefreshTokenRequestDTO true "请求体"
// @Success 200 {object} identity.RefreshTokenResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/auth/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	// 使用全局JWT中间件实例的刷新令牌处理器
	jwtMiddlewareInstance.RefreshHandler(ctx, c)
}

// CreateUser
// @Summary 创建用户
// @Description 管理员创建新用户账户
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.CreateUserRequestDTO true "请求体"
// @Success 200 {object} identity.UserProfileResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 获取当前用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	// 调用业务服务层
	resp, err := identityService.CreateUser(ctx, &req, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "创建用户失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetUser
// @Summary 获取用户信息
// @Description 根据用户ID获取用户详细信息
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Success 200 {object} identity.UserProfileResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID} [GET]
func GetUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层获取用户信息
	resp, err := identityService.GetUser(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取用户信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetMe
// @Summary 获取当前用户信息
// @Description 获取当前登录用户的详细信息
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Success 200 {object} identity.UserProfileResponseDTO "成功"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/me [GET]
func GetMe(ctx context.Context, c *app.RequestContext) {
	var err error

	// 获取用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetMe(ctx, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "获取当前用户信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UpdateUser
// @Summary 更新用户信息
// @Description 更新指定用户的基本信息
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param req body identity.UpdateUserRequestDTO true "请求体"
// @Success 200 {object} identity.UserProfileResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID} [PUT]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 获取当前用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	resp, err := identityService.UpdateUser(ctx, &req, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "更新用户信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UpdateMe
// @Summary 更新当前用户信息
// @Description 用户更新自己的基本信息（从认证上下文获取用户ID）
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.UpdateMeRequestDTO true "请求体"
// @Success 200 {object} identity.UserProfileResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/me [PUT]
func UpdateMe(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateMeRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 获取用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	// 调用业务服务层
	resp, err := identityService.UpdateMe(ctx, &req, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "更新当前用户信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// DeleteUser
// @Summary 删除用户
// @Description 软删除指定用户（管理员权限）
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param req body identity.DeleteUserRequestDTO false "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID} [DELETE]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.DeleteUser(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "删除用户失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ListUsers
// @Summary 获取用户列表
// @Description 分页查询用户列表，支持按组织、状态等条件筛选
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param page query int false "页码" default(1)
// @Param limit query int false "每页数量" default(20)
// @Param search query string false "搜索关键词"
// @Param filter query string false "字段级过滤"
// @Param sort query string false "排序规则"
// @Param fields query string false "指定返回字段"
// @Param include_total query bool false "是否返回总数" default(false)
// @Param organization_id query string false "按组织ID筛选"
// @Param status query int false "按用户状态筛选"
// @Param fetch_all query bool false "是否获取所有数据（不分页）" default(false)
// @Success 200 {object} identity.ListUsersResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ListUsersRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 获取当前权限
	permission, authErr := auth_context.GetCurrentPermission(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	if permission == "view_own_hospital" {
		organizationID, authErr := auth_context.GetCurrentOrganizationID(c)
		if !authErr {
			errors.AbortWithError(c, errors.ErrJWTValidationFail)
			return
		}
		req.OrganizationID = &organizationID
	}

	// 调用业务服务层
	resp, err := identityService.ListUsers(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "查询用户列表失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// SearchUsers
// @Summary 搜索用户
// @Description 按关键词搜索用户
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param page query int false "页码" default(1)
// @Param limit query int false "每页数量" default(20)
// @Param search query string false "搜索关键词"
// @Param filter query string false "字段级过滤"
// @Param sort query string false "排序规则"
// @Param fields query string false "指定返回字段"
// @Param include_total query bool false "是否返回总数" default(false)
// @Param organization_id query string false "按组织ID筛选"
// @Success 200 {object} identity.SearchUsersResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/search [GET]
func SearchUsers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.SearchUsersRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.SearchUsers(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "搜索用户失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ChangeUserStatus
// @Summary 变更用户状态
// @Description 管理员变更用户状态（激活、停用、锁定等）
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param req body identity.ChangeUserStatusRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID}/status [PUT]
func ChangeUserStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ChangeUserStatusRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.ChangeUserStatus(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "修改用户状态失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UnlockUser
// @Summary 解锁用户
// @Description 管理员解锁被锁定的用户
// @Tags 用户管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param req body identity.UnlockUserRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID}/unlock [PUT]
func UnlockUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UnlockUserRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.UnlockUser(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "解锁用户失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetUserMemberships
// @Summary 获取用户成员关系
// @Description 获取指定用户的所有组织成员关系
// @Tags 成员关系管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param userID path string true "用户ID"
// @Param page query int false "页码" default(1)
// @Param limit query int false "每页数量" default(20)
// @Param search query string false "搜索关键词"
// @Param filter query string false "字段级过滤"
// @Param sort query string false "排序规则"
// @Param fields query string false "指定返回字段"
// @Param include_total query bool false "是否返回总数" default(false)
// @Success 200 {object} identity.GetUserMembershipsResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "用户未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID}/memberships [GET]
func GetUserMemberships(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetUserMembershipsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetUserMemberships(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取用户成员关系列表失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// CreateOrganization
// @Summary 创建组织
// @Description 创建新的组织机构
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.CreateOrganizationRequestDTO true "请求体"
// @Success 200 {object} identity.OrganizationResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations [POST]
func CreateOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.CreateOrganization(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "创建组织失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetOrganization
// @Summary 获取组织信息
// @Description 根据组织ID获取组织详细信息
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param organizationID path string true "组织ID"
// @Success 200 {object} identity.OrganizationResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "组织未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations/{organizationID} [GET]
func GetOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetOrganization(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取组织信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UpdateOrganization
// @Summary 更新组织信息
// @Description 更新指定组织的信息
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param organizationID path string true "组织ID"
// @Param req body identity.UpdateOrganizationRequestDTO true "请求体"
// @Success 200 {object} identity.OrganizationResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "组织未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations/{organizationID} [PUT]
func UpdateOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.UpdateOrganization(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "更新组织信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// DeleteOrganization
// @Summary 删除组织
// @Description 软删除指定组织
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.DeleteOrganizationRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "组织未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations/{organizationID} [DELETE]
func DeleteOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.DeleteOrganization(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "删除组织失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// ListOrganizations
// @Summary 获取组织列表
// @Description 分页查询组织列表，支持按父组织筛选
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param page query int false "页码" default(1)
// @Param limit query int false "每页数量" default(20)
// @Param search query string false "搜索关键词"
// @Param filter query string false "字段级过滤"
// @Param sort query string false "排序规则"
// @Param fields query string false "指定返回字段"
// @Param include_total query bool false "是否返回总数" default(false)
// @Param parent_id query string false "按父组织ID筛选"
// @Success 200 {object} identity.ListOrganizationsResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations [GET]
func ListOrganizations(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.ListOrganizationsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.ListOrganizations(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取组织列表失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// CreateDepartment
// @Summary 创建部门
// @Description 在指定组织下创建新部门
// @Tags 部门管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.CreateDepartmentRequestDTO true "请求体"
// @Success 200 {object} identity.DepartmentResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/departments [POST]
func CreateDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.CreateDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.CreateDepartment(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "创建部门失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetDepartment
// @Summary 获取部门信息
// @Description 根据部门ID获取部门详细信息
// @Tags 部门管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param departmentID path string true "部门ID"
// @Success 200 {object} identity.DepartmentResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "部门未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/departments/{departmentID} [GET]
func GetDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetDepartment(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取部门信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UpdateDepartment
// @Summary 更新部门信息
// @Description 更新指定部门的信息
// @Tags 部门管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param departmentID path string true "部门ID"
// @Param req body identity.UpdateDepartmentRequestDTO true "请求体"
// @Success 200 {object} identity.DepartmentResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "部门未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/departments/{departmentID} [PUT]
func UpdateDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UpdateDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.UpdateDepartment(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "更新部门信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// DeleteDepartment
// @Summary 删除部门
// @Description 软删除指定部门
// @Tags 部门管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param departmentID path string true "部门ID"
// @Param req body identity.DeleteDepartmentRequestDTO true "请求体"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "部门未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/departments/{departmentID} [DELETE]
func DeleteDepartment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteDepartmentRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.DeleteDepartment(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "删除部门失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetOrganizationDepartments
// @Summary 获取组织部门列表
// @Description 获取指定组织下的所有部门
// @Tags 部门管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param organizationID path string true "组织ID"
// @Param page query int false "页码" default(1)
// @Param limit query int false "每页数量" default(20)
// @Param search query string false "搜索关键词"
// @Param filter query string false "字段级过滤"
// @Param sort query string false "排序规则"
// @Param fields query string false "指定返回字段"
// @Param include_total query bool false "是否返回总数" default(false)
// @Success 200 {object} identity.GetOrganizationDepartmentsResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "组织未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations/{organizationID}/departments [GET]
func GetOrganizationDepartments(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationDepartmentsRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		// 参数绑定和验证错误，使用统一错误处理
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetOrganizationDepartments(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取组织部门列表失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetPrimaryMembership .
// @Summary 获取用户主成员关系
// @Description 获取指定用户的主成员关系
// @Tags 成员关系管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param req body identity.GetPrimaryMembershipRequestDTO true "请求体"
// @Success 200 {object} identity.UserMembershipResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "主成员关系未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/users/{userID}/primary-membership [GET]
func GetPrimaryMembership(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetPrimaryMembershipRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetPrimaryMembership(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取用户主成员关系失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// UploadTemporaryLogo
// @Summary 上传临时Logo
// @Description 上传组织Logo文件到临时存储（7天后自动过期），返回Logo元数据和预签名下载URL
// @Tags 组织管理
// @Accept multipart/form-data
// @Produce json
// @Security ApiKeyAuth
// @Param file_name formData string true "文件名"
// @Param file_content formData file true "文件内容"
// @Param mime_type formData string false "MIME类型"
// @Success 200 {object} identity.OrganizationLogoResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 413 {object} errors.Error "文件过大"
// @Failure 415 {object} errors.Error "不支持的文件类型"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organization-logos/temporary [POST]
func UploadTemporaryLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.UploadTemporaryLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	fileContent, err := c.FormFile("file_content")
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage("文件不能为空"))
		return
	}
	file, err := fileContent.Open()
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage("无法打开上传的文件"))
		return
	}
	defer file.Close()

	fileContentByte := make([]byte, fileContent.Size)
	_, err = file.Read(fileContentByte)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage("读取上传的文件失败"))
		return
	}
	req.FileContent = fileContentByte

	// 获取当前用户ID
	userID, authErr := auth_context.GetCurrentUserProfileID(c)
	if !authErr {
		errors.AbortWithError(c, errors.ErrJWTValidationFail)
		return
	}

	// 调用业务服务层
	resp, err := identityService.UploadTemporaryLogo(ctx, &req, userID)
	if err != nil {
		errors.HandleServiceError(c, err, "上传临时Logo失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// GetOrganizationLogo
// @Summary 获取Logo信息
// @Description 根据Logo ID获取Logo元数据和预签名下载URL（有效期7天）
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param logoID path string true "Logo ID"
// @Success 200 {object} identity.OrganizationLogoResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 404 {object} errors.Error "Logo未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organization-logos/{logoID} [GET]
func GetOrganizationLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.GetOrganizationLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.GetOrganizationLogo(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "获取Logo信息失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// DeleteOrganizationLogo
// @Summary 删除Logo
// @Description 删除Logo文件和数据库记录（软删除），同时删除S3存储的文件
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param logoID path string true "Logo ID"
// @Success 200 {object} http_base.OperationStatusResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "Logo未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organization-logos/{logoID} [DELETE]
func DeleteOrganizationLogo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.DeleteOrganizationLogoRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.DeleteOrganizationLogo(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "删除Logo失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}

// BindLogoToOrganization
// @Summary 绑定Logo到组织
// @Description 将临时Logo绑定到组织，Logo状态从临时变更为永久保存，并更新组织的Logo信息
// @Tags 组织管理
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param organizationID path string true "组织ID"
// @Param req body identity.BindLogoToOrganizationRequestDTO true "请求体"
// @Success 200 {object} identity.OrganizationResponseDTO "成功"
// @Failure 400 {object} errors.Error "请求参数错误"
// @Failure 401 {object} errors.Error "认证失败"
// @Failure 403 {object} errors.Error "权限不足"
// @Failure 404 {object} errors.Error "Logo或组织未找到"
// @Failure 500 {object} errors.Error "内部错误"
// @Router /api/v1/identity/organizations/{organizationID}/logo [PUT]
func BindLogoToOrganization(ctx context.Context, c *app.RequestContext) {
	var err error
	var req identity.BindLogoToOrganizationRequestDTO
	err = c.BindAndValidate(&req)
	if err != nil {
		errors.AbortWithError(c, errors.ErrInvalidParams.WithMessage(err.Error()))
		return
	}

	// 调用业务服务层
	resp, err := identityService.BindLogoToOrganization(ctx, &req)
	if err != nil {
		errors.HandleServiceError(c, err, "绑定Logo到组织失败")
		return
	}

	errors.JSON(c, consts.StatusOK, resp)
}
