// Code generated by Kitex v0.15.2. DO NOT EDIT.

package identityservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	core "github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/core"
	identity_srv "github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/identity_srv"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Login(ctx context.Context, req *identity_srv.LoginRequest, callOptions ...callopt.Option) (r *identity_srv.LoginResponse, err error)
	ChangePassword(ctx context.Context, req *identity_srv.ChangePasswordRequest, callOptions ...callopt.Option) (err error)
	ResetPassword(ctx context.Context, req *identity_srv.ResetPasswordRequest, callOptions ...callopt.Option) (err error)
	ForcePasswordChange(ctx context.Context, req *identity_srv.ForcePasswordChangeRequest, callOptions ...callopt.Option) (err error)
	CreateUser(ctx context.Context, req *identity_srv.CreateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error)
	GetUser(ctx context.Context, req *identity_srv.GetUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error)
	UpdateUser(ctx context.Context, req *identity_srv.UpdateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error)
	DeleteUser(ctx context.Context, req *identity_srv.DeleteUserRequest, callOptions ...callopt.Option) (err error)
	ListUsers(ctx context.Context, req *identity_srv.ListUsersRequest, callOptions ...callopt.Option) (r *identity_srv.ListUsersResponse, err error)
	SearchUsers(ctx context.Context, req *identity_srv.SearchUsersRequest, callOptions ...callopt.Option) (r *identity_srv.SearchUsersResponse, err error)
	ChangeUserStatus(ctx context.Context, req *identity_srv.ChangeUserStatusRequest, callOptions ...callopt.Option) (err error)
	UnlockUser(ctx context.Context, req *identity_srv.UnlockUserRequest, callOptions ...callopt.Option) (err error)
	CreateOrganization(ctx context.Context, req *identity_srv.CreateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error)
	GetOrganization(ctx context.Context, req *identity_srv.GetOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error)
	UpdateOrganization(ctx context.Context, req *identity_srv.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error)
	DeleteOrganization(ctx context.Context, organizationID core.UUID, callOptions ...callopt.Option) (err error)
	ListOrganizations(ctx context.Context, req *identity_srv.ListOrganizationsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOrganizationsResponse, err error)
	AddMembership(ctx context.Context, req *identity_srv.AddMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error)
	UpdateMembership(ctx context.Context, req *identity_srv.UpdateMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error)
	RemoveMembership(ctx context.Context, membershipID core.UUID, callOptions ...callopt.Option) (err error)
	GetMembership(ctx context.Context, membershipID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error)
	GetUserMemberships(ctx context.Context, req *identity_srv.GetUserMembershipsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMembershipsResponse, err error)
	GetPrimaryMembership(ctx context.Context, userID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error)
	CheckMembership(ctx context.Context, req *identity_srv.CheckMembershipRequest, callOptions ...callopt.Option) (r bool, err error)
	CreateDepartment(ctx context.Context, req *identity_srv.CreateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error)
	GetDepartment(ctx context.Context, req *identity_srv.GetDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error)
	UpdateDepartment(ctx context.Context, req *identity_srv.UpdateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error)
	DeleteDepartment(ctx context.Context, departmentID core.UUID, callOptions ...callopt.Option) (err error)
	GetOrganizationDepartments(ctx context.Context, req *identity_srv.GetOrganizationDepartmentsRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationDepartmentsResponse, err error)
	UploadTemporaryLogo(ctx context.Context, req *identity_srv.UploadTemporaryLogoRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error)
	GetOrganizationLogo(ctx context.Context, req *identity_srv.GetOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error)
	DeleteOrganizationLogo(ctx context.Context, req *identity_srv.DeleteOrganizationLogoRequest, callOptions ...callopt.Option) (err error)
	BindLogoToOrganization(ctx context.Context, req *identity_srv.BindLogoToOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error)
	CreateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionCreateRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error)
	UpdateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionUpdateRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error)
	DeleteRoleDefinition(ctx context.Context, roleID core.UUID, callOptions ...callopt.Option) (err error)
	GetRoleDefinition(ctx context.Context, roleID core.UUID, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error)
	ListRoleDefinitions(ctx context.Context, req *identity_srv.RoleDefinitionQueryRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinitionListResponse, err error)
	AssignRoleToUser(ctx context.Context, req *identity_srv.AssignRoleToUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignmentResponse, err error)
	UpdateUserRoleAssignment(ctx context.Context, req *identity_srv.UpdateUserRoleAssignmentRequest, callOptions ...callopt.Option) (err error)
	RevokeRoleFromUser(ctx context.Context, req *identity_srv.RevokeRoleFromUserRequest, callOptions ...callopt.Option) (err error)
	GetLastUserRoleAssignment(ctx context.Context, userID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignment, err error)
	ListUserRoleAssignments(ctx context.Context, req *identity_srv.UserRoleQueryRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleListResponse, err error)
	GetUsersByRole(ctx context.Context, req *identity_srv.GetUsersByRoleRequest, callOptions ...callopt.Option) (r *identity_srv.GetUsersByRoleResponse, err error)
	BatchBindUsersToRole(ctx context.Context, req *identity_srv.BatchBindUsersToRoleRequest, callOptions ...callopt.Option) (r *identity_srv.BatchBindUsersToRoleResponse, err error)
	BatchGetUserRoles(ctx context.Context, req *identity_srv.BatchGetUserRolesRequest, callOptions ...callopt.Option) (r *identity_srv.BatchGetUserRolesResponse, err error)
	UploadMenu(ctx context.Context, req *identity_srv.UploadMenuRequest, callOptions ...callopt.Option) (err error)
	GetMenuTree(ctx context.Context, callOptions ...callopt.Option) (r *identity_srv.GetMenuTreeResponse, err error)
	ConfigureRoleMenus(ctx context.Context, req *identity_srv.ConfigureRoleMenusRequest, callOptions ...callopt.Option) (r *identity_srv.ConfigureRoleMenusResponse, err error)
	GetRoleMenuTree(ctx context.Context, req *identity_srv.GetRoleMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuTreeResponse, err error)
	GetUserMenuTree(ctx context.Context, req *identity_srv.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuTreeResponse, err error)
	GetRoleMenuPermissions(ctx context.Context, req *identity_srv.GetRoleMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuPermissionsResponse, err error)
	HasMenuPermission(ctx context.Context, req *identity_srv.HasMenuPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.HasMenuPermissionResponse, err error)
	GetUserMenuPermissions(ctx context.Context, req *identity_srv.GetUserMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuPermissionsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kIdentityServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kIdentityServiceClient struct {
	*kClient
}

func (p *kIdentityServiceClient) Login(ctx context.Context, req *identity_srv.LoginRequest, callOptions ...callopt.Option) (r *identity_srv.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kIdentityServiceClient) ChangePassword(ctx context.Context, req *identity_srv.ChangePasswordRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, req)
}

func (p *kIdentityServiceClient) ResetPassword(ctx context.Context, req *identity_srv.ResetPasswordRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ResetPassword(ctx, req)
}

func (p *kIdentityServiceClient) ForcePasswordChange(ctx context.Context, req *identity_srv.ForcePasswordChangeRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ForcePasswordChange(ctx, req)
}

func (p *kIdentityServiceClient) CreateUser(ctx context.Context, req *identity_srv.CreateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, req)
}

func (p *kIdentityServiceClient) GetUser(ctx context.Context, req *identity_srv.GetUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}

func (p *kIdentityServiceClient) UpdateUser(ctx context.Context, req *identity_srv.UpdateUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserProfile, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, req)
}

func (p *kIdentityServiceClient) DeleteUser(ctx context.Context, req *identity_srv.DeleteUserRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, req)
}

func (p *kIdentityServiceClient) ListUsers(ctx context.Context, req *identity_srv.ListUsersRequest, callOptions ...callopt.Option) (r *identity_srv.ListUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, req)
}

func (p *kIdentityServiceClient) SearchUsers(ctx context.Context, req *identity_srv.SearchUsersRequest, callOptions ...callopt.Option) (r *identity_srv.SearchUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUsers(ctx, req)
}

func (p *kIdentityServiceClient) ChangeUserStatus(ctx context.Context, req *identity_srv.ChangeUserStatusRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeUserStatus(ctx, req)
}

func (p *kIdentityServiceClient) UnlockUser(ctx context.Context, req *identity_srv.UnlockUserRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnlockUser(ctx, req)
}

func (p *kIdentityServiceClient) CreateOrganization(ctx context.Context, req *identity_srv.CreateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrganization(ctx, req)
}

func (p *kIdentityServiceClient) GetOrganization(ctx context.Context, req *identity_srv.GetOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganization(ctx, req)
}

func (p *kIdentityServiceClient) UpdateOrganization(ctx context.Context, req *identity_srv.UpdateOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.Organization, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrganization(ctx, req)
}

func (p *kIdentityServiceClient) DeleteOrganization(ctx context.Context, organizationID core.UUID, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrganization(ctx, organizationID)
}

func (p *kIdentityServiceClient) ListOrganizations(ctx context.Context, req *identity_srv.ListOrganizationsRequest, callOptions ...callopt.Option) (r *identity_srv.ListOrganizationsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOrganizations(ctx, req)
}

func (p *kIdentityServiceClient) AddMembership(ctx context.Context, req *identity_srv.AddMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddMembership(ctx, req)
}

func (p *kIdentityServiceClient) UpdateMembership(ctx context.Context, req *identity_srv.UpdateMembershipRequest, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateMembership(ctx, req)
}

func (p *kIdentityServiceClient) RemoveMembership(ctx context.Context, membershipID core.UUID, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RemoveMembership(ctx, membershipID)
}

func (p *kIdentityServiceClient) GetMembership(ctx context.Context, membershipID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMembership(ctx, membershipID)
}

func (p *kIdentityServiceClient) GetUserMemberships(ctx context.Context, req *identity_srv.GetUserMembershipsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMembershipsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMemberships(ctx, req)
}

func (p *kIdentityServiceClient) GetPrimaryMembership(ctx context.Context, userID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserMembership, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPrimaryMembership(ctx, userID)
}

func (p *kIdentityServiceClient) CheckMembership(ctx context.Context, req *identity_srv.CheckMembershipRequest, callOptions ...callopt.Option) (r bool, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckMembership(ctx, req)
}

func (p *kIdentityServiceClient) CreateDepartment(ctx context.Context, req *identity_srv.CreateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateDepartment(ctx, req)
}

func (p *kIdentityServiceClient) GetDepartment(ctx context.Context, req *identity_srv.GetDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDepartment(ctx, req)
}

func (p *kIdentityServiceClient) UpdateDepartment(ctx context.Context, req *identity_srv.UpdateDepartmentRequest, callOptions ...callopt.Option) (r *identity_srv.Department, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateDepartment(ctx, req)
}

func (p *kIdentityServiceClient) DeleteDepartment(ctx context.Context, departmentID core.UUID, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteDepartment(ctx, departmentID)
}

func (p *kIdentityServiceClient) GetOrganizationDepartments(ctx context.Context, req *identity_srv.GetOrganizationDepartmentsRequest, callOptions ...callopt.Option) (r *identity_srv.GetOrganizationDepartmentsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationDepartments(ctx, req)
}

func (p *kIdentityServiceClient) UploadTemporaryLogo(ctx context.Context, req *identity_srv.UploadTemporaryLogoRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadTemporaryLogo(ctx, req)
}

func (p *kIdentityServiceClient) GetOrganizationLogo(ctx context.Context, req *identity_srv.GetOrganizationLogoRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrganizationLogo(ctx, req)
}

func (p *kIdentityServiceClient) DeleteOrganizationLogo(ctx context.Context, req *identity_srv.DeleteOrganizationLogoRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteOrganizationLogo(ctx, req)
}

func (p *kIdentityServiceClient) BindLogoToOrganization(ctx context.Context, req *identity_srv.BindLogoToOrganizationRequest, callOptions ...callopt.Option) (r *identity_srv.OrganizationLogo, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindLogoToOrganization(ctx, req)
}

func (p *kIdentityServiceClient) CreateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionCreateRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateRoleDefinition(ctx, req)
}

func (p *kIdentityServiceClient) UpdateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionUpdateRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateRoleDefinition(ctx, req)
}

func (p *kIdentityServiceClient) DeleteRoleDefinition(ctx context.Context, roleID core.UUID, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteRoleDefinition(ctx, roleID)
}

func (p *kIdentityServiceClient) GetRoleDefinition(ctx context.Context, roleID core.UUID, callOptions ...callopt.Option) (r *identity_srv.RoleDefinition, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleDefinition(ctx, roleID)
}

func (p *kIdentityServiceClient) ListRoleDefinitions(ctx context.Context, req *identity_srv.RoleDefinitionQueryRequest, callOptions ...callopt.Option) (r *identity_srv.RoleDefinitionListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListRoleDefinitions(ctx, req)
}

func (p *kIdentityServiceClient) AssignRoleToUser(ctx context.Context, req *identity_srv.AssignRoleToUserRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignmentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AssignRoleToUser(ctx, req)
}

func (p *kIdentityServiceClient) UpdateUserRoleAssignment(ctx context.Context, req *identity_srv.UpdateUserRoleAssignmentRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserRoleAssignment(ctx, req)
}

func (p *kIdentityServiceClient) RevokeRoleFromUser(ctx context.Context, req *identity_srv.RevokeRoleFromUserRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RevokeRoleFromUser(ctx, req)
}

func (p *kIdentityServiceClient) GetLastUserRoleAssignment(ctx context.Context, userID core.UUID, callOptions ...callopt.Option) (r *identity_srv.UserRoleAssignment, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLastUserRoleAssignment(ctx, userID)
}

func (p *kIdentityServiceClient) ListUserRoleAssignments(ctx context.Context, req *identity_srv.UserRoleQueryRequest, callOptions ...callopt.Option) (r *identity_srv.UserRoleListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUserRoleAssignments(ctx, req)
}

func (p *kIdentityServiceClient) GetUsersByRole(ctx context.Context, req *identity_srv.GetUsersByRoleRequest, callOptions ...callopt.Option) (r *identity_srv.GetUsersByRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUsersByRole(ctx, req)
}

func (p *kIdentityServiceClient) BatchBindUsersToRole(ctx context.Context, req *identity_srv.BatchBindUsersToRoleRequest, callOptions ...callopt.Option) (r *identity_srv.BatchBindUsersToRoleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchBindUsersToRole(ctx, req)
}

func (p *kIdentityServiceClient) BatchGetUserRoles(ctx context.Context, req *identity_srv.BatchGetUserRolesRequest, callOptions ...callopt.Option) (r *identity_srv.BatchGetUserRolesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchGetUserRoles(ctx, req)
}

func (p *kIdentityServiceClient) UploadMenu(ctx context.Context, req *identity_srv.UploadMenuRequest, callOptions ...callopt.Option) (err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadMenu(ctx, req)
}

func (p *kIdentityServiceClient) GetMenuTree(ctx context.Context, callOptions ...callopt.Option) (r *identity_srv.GetMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMenuTree(ctx)
}

func (p *kIdentityServiceClient) ConfigureRoleMenus(ctx context.Context, req *identity_srv.ConfigureRoleMenusRequest, callOptions ...callopt.Option) (r *identity_srv.ConfigureRoleMenusResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConfigureRoleMenus(ctx, req)
}

func (p *kIdentityServiceClient) GetRoleMenuTree(ctx context.Context, req *identity_srv.GetRoleMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleMenuTree(ctx, req)
}

func (p *kIdentityServiceClient) GetUserMenuTree(ctx context.Context, req *identity_srv.GetUserMenuTreeRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuTreeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMenuTree(ctx, req)
}

func (p *kIdentityServiceClient) GetRoleMenuPermissions(ctx context.Context, req *identity_srv.GetRoleMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetRoleMenuPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetRoleMenuPermissions(ctx, req)
}

func (p *kIdentityServiceClient) HasMenuPermission(ctx context.Context, req *identity_srv.HasMenuPermissionRequest, callOptions ...callopt.Option) (r *identity_srv.HasMenuPermissionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HasMenuPermission(ctx, req)
}

func (p *kIdentityServiceClient) GetUserMenuPermissions(ctx context.Context, req *identity_srv.GetUserMenuPermissionsRequest, callOptions ...callopt.Option) (r *identity_srv.GetUserMenuPermissionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserMenuPermissions(ctx, req)
}
