// Code generated by Kitex v0.15.2. DO NOT EDIT.

package identityservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	core "github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/core"
	identity_srv "github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/identity_srv"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newIdentityServiceLoginArgs,
		newIdentityServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newIdentityServiceChangePasswordArgs,
		newIdentityServiceChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ResetPassword": kitex.NewMethodInfo(
		resetPasswordHandler,
		newIdentityServiceResetPasswordArgs,
		newIdentityServiceResetPasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ForcePasswordChange": kitex.NewMethodInfo(
		forcePasswordChangeHandler,
		newIdentityServiceForcePasswordChangeArgs,
		newIdentityServiceForcePasswordChangeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateUser": kitex.NewMethodInfo(
		createUserHandler,
		newIdentityServiceCreateUserArgs,
		newIdentityServiceCreateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUser": kitex.NewMethodInfo(
		getUserHandler,
		newIdentityServiceGetUserArgs,
		newIdentityServiceGetUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUser": kitex.NewMethodInfo(
		updateUserHandler,
		newIdentityServiceUpdateUserArgs,
		newIdentityServiceUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUser": kitex.NewMethodInfo(
		deleteUserHandler,
		newIdentityServiceDeleteUserArgs,
		newIdentityServiceDeleteUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListUsers": kitex.NewMethodInfo(
		listUsersHandler,
		newIdentityServiceListUsersArgs,
		newIdentityServiceListUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SearchUsers": kitex.NewMethodInfo(
		searchUsersHandler,
		newIdentityServiceSearchUsersArgs,
		newIdentityServiceSearchUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeUserStatus": kitex.NewMethodInfo(
		changeUserStatusHandler,
		newIdentityServiceChangeUserStatusArgs,
		newIdentityServiceChangeUserStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnlockUser": kitex.NewMethodInfo(
		unlockUserHandler,
		newIdentityServiceUnlockUserArgs,
		newIdentityServiceUnlockUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateOrganization": kitex.NewMethodInfo(
		createOrganizationHandler,
		newIdentityServiceCreateOrganizationArgs,
		newIdentityServiceCreateOrganizationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrganization": kitex.NewMethodInfo(
		getOrganizationHandler,
		newIdentityServiceGetOrganizationArgs,
		newIdentityServiceGetOrganizationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateOrganization": kitex.NewMethodInfo(
		updateOrganizationHandler,
		newIdentityServiceUpdateOrganizationArgs,
		newIdentityServiceUpdateOrganizationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteOrganization": kitex.NewMethodInfo(
		deleteOrganizationHandler,
		newIdentityServiceDeleteOrganizationArgs,
		newIdentityServiceDeleteOrganizationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListOrganizations": kitex.NewMethodInfo(
		listOrganizationsHandler,
		newIdentityServiceListOrganizationsArgs,
		newIdentityServiceListOrganizationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddMembership": kitex.NewMethodInfo(
		addMembershipHandler,
		newIdentityServiceAddMembershipArgs,
		newIdentityServiceAddMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateMembership": kitex.NewMethodInfo(
		updateMembershipHandler,
		newIdentityServiceUpdateMembershipArgs,
		newIdentityServiceUpdateMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RemoveMembership": kitex.NewMethodInfo(
		removeMembershipHandler,
		newIdentityServiceRemoveMembershipArgs,
		newIdentityServiceRemoveMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMembership": kitex.NewMethodInfo(
		getMembershipHandler,
		newIdentityServiceGetMembershipArgs,
		newIdentityServiceGetMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserMemberships": kitex.NewMethodInfo(
		getUserMembershipsHandler,
		newIdentityServiceGetUserMembershipsArgs,
		newIdentityServiceGetUserMembershipsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPrimaryMembership": kitex.NewMethodInfo(
		getPrimaryMembershipHandler,
		newIdentityServiceGetPrimaryMembershipArgs,
		newIdentityServiceGetPrimaryMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CheckMembership": kitex.NewMethodInfo(
		checkMembershipHandler,
		newIdentityServiceCheckMembershipArgs,
		newIdentityServiceCheckMembershipResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateDepartment": kitex.NewMethodInfo(
		createDepartmentHandler,
		newIdentityServiceCreateDepartmentArgs,
		newIdentityServiceCreateDepartmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDepartment": kitex.NewMethodInfo(
		getDepartmentHandler,
		newIdentityServiceGetDepartmentArgs,
		newIdentityServiceGetDepartmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateDepartment": kitex.NewMethodInfo(
		updateDepartmentHandler,
		newIdentityServiceUpdateDepartmentArgs,
		newIdentityServiceUpdateDepartmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteDepartment": kitex.NewMethodInfo(
		deleteDepartmentHandler,
		newIdentityServiceDeleteDepartmentArgs,
		newIdentityServiceDeleteDepartmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrganizationDepartments": kitex.NewMethodInfo(
		getOrganizationDepartmentsHandler,
		newIdentityServiceGetOrganizationDepartmentsArgs,
		newIdentityServiceGetOrganizationDepartmentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadTemporaryLogo": kitex.NewMethodInfo(
		uploadTemporaryLogoHandler,
		newIdentityServiceUploadTemporaryLogoArgs,
		newIdentityServiceUploadTemporaryLogoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrganizationLogo": kitex.NewMethodInfo(
		getOrganizationLogoHandler,
		newIdentityServiceGetOrganizationLogoArgs,
		newIdentityServiceGetOrganizationLogoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteOrganizationLogo": kitex.NewMethodInfo(
		deleteOrganizationLogoHandler,
		newIdentityServiceDeleteOrganizationLogoArgs,
		newIdentityServiceDeleteOrganizationLogoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindLogoToOrganization": kitex.NewMethodInfo(
		bindLogoToOrganizationHandler,
		newIdentityServiceBindLogoToOrganizationArgs,
		newIdentityServiceBindLogoToOrganizationResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateRoleDefinition": kitex.NewMethodInfo(
		createRoleDefinitionHandler,
		newIdentityServiceCreateRoleDefinitionArgs,
		newIdentityServiceCreateRoleDefinitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateRoleDefinition": kitex.NewMethodInfo(
		updateRoleDefinitionHandler,
		newIdentityServiceUpdateRoleDefinitionArgs,
		newIdentityServiceUpdateRoleDefinitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteRoleDefinition": kitex.NewMethodInfo(
		deleteRoleDefinitionHandler,
		newIdentityServiceDeleteRoleDefinitionArgs,
		newIdentityServiceDeleteRoleDefinitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRoleDefinition": kitex.NewMethodInfo(
		getRoleDefinitionHandler,
		newIdentityServiceGetRoleDefinitionArgs,
		newIdentityServiceGetRoleDefinitionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListRoleDefinitions": kitex.NewMethodInfo(
		listRoleDefinitionsHandler,
		newIdentityServiceListRoleDefinitionsArgs,
		newIdentityServiceListRoleDefinitionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AssignRoleToUser": kitex.NewMethodInfo(
		assignRoleToUserHandler,
		newIdentityServiceAssignRoleToUserArgs,
		newIdentityServiceAssignRoleToUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserRoleAssignment": kitex.NewMethodInfo(
		updateUserRoleAssignmentHandler,
		newIdentityServiceUpdateUserRoleAssignmentArgs,
		newIdentityServiceUpdateUserRoleAssignmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RevokeRoleFromUser": kitex.NewMethodInfo(
		revokeRoleFromUserHandler,
		newIdentityServiceRevokeRoleFromUserArgs,
		newIdentityServiceRevokeRoleFromUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLastUserRoleAssignment": kitex.NewMethodInfo(
		getLastUserRoleAssignmentHandler,
		newIdentityServiceGetLastUserRoleAssignmentArgs,
		newIdentityServiceGetLastUserRoleAssignmentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListUserRoleAssignments": kitex.NewMethodInfo(
		listUserRoleAssignmentsHandler,
		newIdentityServiceListUserRoleAssignmentsArgs,
		newIdentityServiceListUserRoleAssignmentsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUsersByRole": kitex.NewMethodInfo(
		getUsersByRoleHandler,
		newIdentityServiceGetUsersByRoleArgs,
		newIdentityServiceGetUsersByRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchBindUsersToRole": kitex.NewMethodInfo(
		batchBindUsersToRoleHandler,
		newIdentityServiceBatchBindUsersToRoleArgs,
		newIdentityServiceBatchBindUsersToRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BatchGetUserRoles": kitex.NewMethodInfo(
		batchGetUserRolesHandler,
		newIdentityServiceBatchGetUserRolesArgs,
		newIdentityServiceBatchGetUserRolesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UploadMenu": kitex.NewMethodInfo(
		uploadMenuHandler,
		newIdentityServiceUploadMenuArgs,
		newIdentityServiceUploadMenuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMenuTree": kitex.NewMethodInfo(
		getMenuTreeHandler,
		newIdentityServiceGetMenuTreeArgs,
		newIdentityServiceGetMenuTreeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ConfigureRoleMenus": kitex.NewMethodInfo(
		configureRoleMenusHandler,
		newIdentityServiceConfigureRoleMenusArgs,
		newIdentityServiceConfigureRoleMenusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRoleMenuTree": kitex.NewMethodInfo(
		getRoleMenuTreeHandler,
		newIdentityServiceGetRoleMenuTreeArgs,
		newIdentityServiceGetRoleMenuTreeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserMenuTree": kitex.NewMethodInfo(
		getUserMenuTreeHandler,
		newIdentityServiceGetUserMenuTreeArgs,
		newIdentityServiceGetUserMenuTreeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetRoleMenuPermissions": kitex.NewMethodInfo(
		getRoleMenuPermissionsHandler,
		newIdentityServiceGetRoleMenuPermissionsArgs,
		newIdentityServiceGetRoleMenuPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"HasMenuPermission": kitex.NewMethodInfo(
		hasMenuPermissionHandler,
		newIdentityServiceHasMenuPermissionArgs,
		newIdentityServiceHasMenuPermissionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserMenuPermissions": kitex.NewMethodInfo(
		getUserMenuPermissionsHandler,
		newIdentityServiceGetUserMenuPermissionsArgs,
		newIdentityServiceGetUserMenuPermissionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	identityServiceServiceInfo                = NewServiceInfo()
	identityServiceServiceInfoForClient       = NewServiceInfoForClient()
	identityServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return identityServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return identityServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return identityServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "IdentityService"
	handlerType := (*identity_srv.IdentityService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "identity_srv",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceLoginArgs)
	realResult := result.(*identity_srv.IdentityServiceLoginResult)
	success, err := handler.(identity_srv.IdentityService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceLoginArgs() interface{} {
	return identity_srv.NewIdentityServiceLoginArgs()
}

func newIdentityServiceLoginResult() interface{} {
	return identity_srv.NewIdentityServiceLoginResult()
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceChangePasswordArgs)

	err := handler.(identity_srv.IdentityService).ChangePassword(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceChangePasswordArgs() interface{} {
	return identity_srv.NewIdentityServiceChangePasswordArgs()
}

func newIdentityServiceChangePasswordResult() interface{} {
	return identity_srv.NewIdentityServiceChangePasswordResult()
}

func resetPasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceResetPasswordArgs)

	err := handler.(identity_srv.IdentityService).ResetPassword(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceResetPasswordArgs() interface{} {
	return identity_srv.NewIdentityServiceResetPasswordArgs()
}

func newIdentityServiceResetPasswordResult() interface{} {
	return identity_srv.NewIdentityServiceResetPasswordResult()
}

func forcePasswordChangeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceForcePasswordChangeArgs)

	err := handler.(identity_srv.IdentityService).ForcePasswordChange(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceForcePasswordChangeArgs() interface{} {
	return identity_srv.NewIdentityServiceForcePasswordChangeArgs()
}

func newIdentityServiceForcePasswordChangeResult() interface{} {
	return identity_srv.NewIdentityServiceForcePasswordChangeResult()
}

func createUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceCreateUserArgs)
	realResult := result.(*identity_srv.IdentityServiceCreateUserResult)
	success, err := handler.(identity_srv.IdentityService).CreateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceCreateUserArgs() interface{} {
	return identity_srv.NewIdentityServiceCreateUserArgs()
}

func newIdentityServiceCreateUserResult() interface{} {
	return identity_srv.NewIdentityServiceCreateUserResult()
}

func getUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetUserArgs)
	realResult := result.(*identity_srv.IdentityServiceGetUserResult)
	success, err := handler.(identity_srv.IdentityService).GetUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetUserArgs() interface{} {
	return identity_srv.NewIdentityServiceGetUserArgs()
}

func newIdentityServiceGetUserResult() interface{} {
	return identity_srv.NewIdentityServiceGetUserResult()
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateUserArgs)
	realResult := result.(*identity_srv.IdentityServiceUpdateUserResult)
	success, err := handler.(identity_srv.IdentityService).UpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUpdateUserArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateUserArgs()
}

func newIdentityServiceUpdateUserResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateUserResult()
}

func deleteUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceDeleteUserArgs)

	err := handler.(identity_srv.IdentityService).DeleteUser(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceDeleteUserArgs() interface{} {
	return identity_srv.NewIdentityServiceDeleteUserArgs()
}

func newIdentityServiceDeleteUserResult() interface{} {
	return identity_srv.NewIdentityServiceDeleteUserResult()
}

func listUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceListUsersArgs)
	realResult := result.(*identity_srv.IdentityServiceListUsersResult)
	success, err := handler.(identity_srv.IdentityService).ListUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceListUsersArgs() interface{} {
	return identity_srv.NewIdentityServiceListUsersArgs()
}

func newIdentityServiceListUsersResult() interface{} {
	return identity_srv.NewIdentityServiceListUsersResult()
}

func searchUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceSearchUsersArgs)
	realResult := result.(*identity_srv.IdentityServiceSearchUsersResult)
	success, err := handler.(identity_srv.IdentityService).SearchUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceSearchUsersArgs() interface{} {
	return identity_srv.NewIdentityServiceSearchUsersArgs()
}

func newIdentityServiceSearchUsersResult() interface{} {
	return identity_srv.NewIdentityServiceSearchUsersResult()
}

func changeUserStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceChangeUserStatusArgs)

	err := handler.(identity_srv.IdentityService).ChangeUserStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceChangeUserStatusArgs() interface{} {
	return identity_srv.NewIdentityServiceChangeUserStatusArgs()
}

func newIdentityServiceChangeUserStatusResult() interface{} {
	return identity_srv.NewIdentityServiceChangeUserStatusResult()
}

func unlockUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUnlockUserArgs)

	err := handler.(identity_srv.IdentityService).UnlockUser(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceUnlockUserArgs() interface{} {
	return identity_srv.NewIdentityServiceUnlockUserArgs()
}

func newIdentityServiceUnlockUserResult() interface{} {
	return identity_srv.NewIdentityServiceUnlockUserResult()
}

func createOrganizationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceCreateOrganizationArgs)
	realResult := result.(*identity_srv.IdentityServiceCreateOrganizationResult)
	success, err := handler.(identity_srv.IdentityService).CreateOrganization(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceCreateOrganizationArgs() interface{} {
	return identity_srv.NewIdentityServiceCreateOrganizationArgs()
}

func newIdentityServiceCreateOrganizationResult() interface{} {
	return identity_srv.NewIdentityServiceCreateOrganizationResult()
}

func getOrganizationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetOrganizationArgs)
	realResult := result.(*identity_srv.IdentityServiceGetOrganizationResult)
	success, err := handler.(identity_srv.IdentityService).GetOrganization(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetOrganizationArgs() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationArgs()
}

func newIdentityServiceGetOrganizationResult() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationResult()
}

func updateOrganizationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateOrganizationArgs)
	realResult := result.(*identity_srv.IdentityServiceUpdateOrganizationResult)
	success, err := handler.(identity_srv.IdentityService).UpdateOrganization(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUpdateOrganizationArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateOrganizationArgs()
}

func newIdentityServiceUpdateOrganizationResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateOrganizationResult()
}

func deleteOrganizationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceDeleteOrganizationArgs)

	err := handler.(identity_srv.IdentityService).DeleteOrganization(ctx, realArg.OrganizationID)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceDeleteOrganizationArgs() interface{} {
	return identity_srv.NewIdentityServiceDeleteOrganizationArgs()
}

func newIdentityServiceDeleteOrganizationResult() interface{} {
	return identity_srv.NewIdentityServiceDeleteOrganizationResult()
}

func listOrganizationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceListOrganizationsArgs)
	realResult := result.(*identity_srv.IdentityServiceListOrganizationsResult)
	success, err := handler.(identity_srv.IdentityService).ListOrganizations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceListOrganizationsArgs() interface{} {
	return identity_srv.NewIdentityServiceListOrganizationsArgs()
}

func newIdentityServiceListOrganizationsResult() interface{} {
	return identity_srv.NewIdentityServiceListOrganizationsResult()
}

func addMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceAddMembershipArgs)
	realResult := result.(*identity_srv.IdentityServiceAddMembershipResult)
	success, err := handler.(identity_srv.IdentityService).AddMembership(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceAddMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceAddMembershipArgs()
}

func newIdentityServiceAddMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceAddMembershipResult()
}

func updateMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateMembershipArgs)
	realResult := result.(*identity_srv.IdentityServiceUpdateMembershipResult)
	success, err := handler.(identity_srv.IdentityService).UpdateMembership(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUpdateMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateMembershipArgs()
}

func newIdentityServiceUpdateMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateMembershipResult()
}

func removeMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceRemoveMembershipArgs)

	err := handler.(identity_srv.IdentityService).RemoveMembership(ctx, realArg.MembershipID)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceRemoveMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceRemoveMembershipArgs()
}

func newIdentityServiceRemoveMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceRemoveMembershipResult()
}

func getMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetMembershipArgs)
	realResult := result.(*identity_srv.IdentityServiceGetMembershipResult)
	success, err := handler.(identity_srv.IdentityService).GetMembership(ctx, realArg.MembershipID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceGetMembershipArgs()
}

func newIdentityServiceGetMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceGetMembershipResult()
}

func getUserMembershipsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetUserMembershipsArgs)
	realResult := result.(*identity_srv.IdentityServiceGetUserMembershipsResult)
	success, err := handler.(identity_srv.IdentityService).GetUserMemberships(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetUserMembershipsArgs() interface{} {
	return identity_srv.NewIdentityServiceGetUserMembershipsArgs()
}

func newIdentityServiceGetUserMembershipsResult() interface{} {
	return identity_srv.NewIdentityServiceGetUserMembershipsResult()
}

func getPrimaryMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetPrimaryMembershipArgs)
	realResult := result.(*identity_srv.IdentityServiceGetPrimaryMembershipResult)
	success, err := handler.(identity_srv.IdentityService).GetPrimaryMembership(ctx, realArg.UserID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetPrimaryMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceGetPrimaryMembershipArgs()
}

func newIdentityServiceGetPrimaryMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceGetPrimaryMembershipResult()
}

func checkMembershipHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceCheckMembershipArgs)
	realResult := result.(*identity_srv.IdentityServiceCheckMembershipResult)
	success, err := handler.(identity_srv.IdentityService).CheckMembership(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = &success
	return nil
}
func newIdentityServiceCheckMembershipArgs() interface{} {
	return identity_srv.NewIdentityServiceCheckMembershipArgs()
}

func newIdentityServiceCheckMembershipResult() interface{} {
	return identity_srv.NewIdentityServiceCheckMembershipResult()
}

func createDepartmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceCreateDepartmentArgs)
	realResult := result.(*identity_srv.IdentityServiceCreateDepartmentResult)
	success, err := handler.(identity_srv.IdentityService).CreateDepartment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceCreateDepartmentArgs() interface{} {
	return identity_srv.NewIdentityServiceCreateDepartmentArgs()
}

func newIdentityServiceCreateDepartmentResult() interface{} {
	return identity_srv.NewIdentityServiceCreateDepartmentResult()
}

func getDepartmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetDepartmentArgs)
	realResult := result.(*identity_srv.IdentityServiceGetDepartmentResult)
	success, err := handler.(identity_srv.IdentityService).GetDepartment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetDepartmentArgs() interface{} {
	return identity_srv.NewIdentityServiceGetDepartmentArgs()
}

func newIdentityServiceGetDepartmentResult() interface{} {
	return identity_srv.NewIdentityServiceGetDepartmentResult()
}

func updateDepartmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateDepartmentArgs)
	realResult := result.(*identity_srv.IdentityServiceUpdateDepartmentResult)
	success, err := handler.(identity_srv.IdentityService).UpdateDepartment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUpdateDepartmentArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateDepartmentArgs()
}

func newIdentityServiceUpdateDepartmentResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateDepartmentResult()
}

func deleteDepartmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceDeleteDepartmentArgs)

	err := handler.(identity_srv.IdentityService).DeleteDepartment(ctx, realArg.DepartmentID)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceDeleteDepartmentArgs() interface{} {
	return identity_srv.NewIdentityServiceDeleteDepartmentArgs()
}

func newIdentityServiceDeleteDepartmentResult() interface{} {
	return identity_srv.NewIdentityServiceDeleteDepartmentResult()
}

func getOrganizationDepartmentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetOrganizationDepartmentsArgs)
	realResult := result.(*identity_srv.IdentityServiceGetOrganizationDepartmentsResult)
	success, err := handler.(identity_srv.IdentityService).GetOrganizationDepartments(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetOrganizationDepartmentsArgs() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationDepartmentsArgs()
}

func newIdentityServiceGetOrganizationDepartmentsResult() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationDepartmentsResult()
}

func uploadTemporaryLogoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUploadTemporaryLogoArgs)
	realResult := result.(*identity_srv.IdentityServiceUploadTemporaryLogoResult)
	success, err := handler.(identity_srv.IdentityService).UploadTemporaryLogo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUploadTemporaryLogoArgs() interface{} {
	return identity_srv.NewIdentityServiceUploadTemporaryLogoArgs()
}

func newIdentityServiceUploadTemporaryLogoResult() interface{} {
	return identity_srv.NewIdentityServiceUploadTemporaryLogoResult()
}

func getOrganizationLogoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetOrganizationLogoArgs)
	realResult := result.(*identity_srv.IdentityServiceGetOrganizationLogoResult)
	success, err := handler.(identity_srv.IdentityService).GetOrganizationLogo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetOrganizationLogoArgs() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationLogoArgs()
}

func newIdentityServiceGetOrganizationLogoResult() interface{} {
	return identity_srv.NewIdentityServiceGetOrganizationLogoResult()
}

func deleteOrganizationLogoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceDeleteOrganizationLogoArgs)

	err := handler.(identity_srv.IdentityService).DeleteOrganizationLogo(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceDeleteOrganizationLogoArgs() interface{} {
	return identity_srv.NewIdentityServiceDeleteOrganizationLogoArgs()
}

func newIdentityServiceDeleteOrganizationLogoResult() interface{} {
	return identity_srv.NewIdentityServiceDeleteOrganizationLogoResult()
}

func bindLogoToOrganizationHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceBindLogoToOrganizationArgs)
	realResult := result.(*identity_srv.IdentityServiceBindLogoToOrganizationResult)
	success, err := handler.(identity_srv.IdentityService).BindLogoToOrganization(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceBindLogoToOrganizationArgs() interface{} {
	return identity_srv.NewIdentityServiceBindLogoToOrganizationArgs()
}

func newIdentityServiceBindLogoToOrganizationResult() interface{} {
	return identity_srv.NewIdentityServiceBindLogoToOrganizationResult()
}

func createRoleDefinitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceCreateRoleDefinitionArgs)
	realResult := result.(*identity_srv.IdentityServiceCreateRoleDefinitionResult)
	success, err := handler.(identity_srv.IdentityService).CreateRoleDefinition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceCreateRoleDefinitionArgs() interface{} {
	return identity_srv.NewIdentityServiceCreateRoleDefinitionArgs()
}

func newIdentityServiceCreateRoleDefinitionResult() interface{} {
	return identity_srv.NewIdentityServiceCreateRoleDefinitionResult()
}

func updateRoleDefinitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateRoleDefinitionArgs)
	realResult := result.(*identity_srv.IdentityServiceUpdateRoleDefinitionResult)
	success, err := handler.(identity_srv.IdentityService).UpdateRoleDefinition(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceUpdateRoleDefinitionArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateRoleDefinitionArgs()
}

func newIdentityServiceUpdateRoleDefinitionResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateRoleDefinitionResult()
}

func deleteRoleDefinitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceDeleteRoleDefinitionArgs)

	err := handler.(identity_srv.IdentityService).DeleteRoleDefinition(ctx, realArg.RoleID)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceDeleteRoleDefinitionArgs() interface{} {
	return identity_srv.NewIdentityServiceDeleteRoleDefinitionArgs()
}

func newIdentityServiceDeleteRoleDefinitionResult() interface{} {
	return identity_srv.NewIdentityServiceDeleteRoleDefinitionResult()
}

func getRoleDefinitionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetRoleDefinitionArgs)
	realResult := result.(*identity_srv.IdentityServiceGetRoleDefinitionResult)
	success, err := handler.(identity_srv.IdentityService).GetRoleDefinition(ctx, realArg.RoleID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetRoleDefinitionArgs() interface{} {
	return identity_srv.NewIdentityServiceGetRoleDefinitionArgs()
}

func newIdentityServiceGetRoleDefinitionResult() interface{} {
	return identity_srv.NewIdentityServiceGetRoleDefinitionResult()
}

func listRoleDefinitionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceListRoleDefinitionsArgs)
	realResult := result.(*identity_srv.IdentityServiceListRoleDefinitionsResult)
	success, err := handler.(identity_srv.IdentityService).ListRoleDefinitions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceListRoleDefinitionsArgs() interface{} {
	return identity_srv.NewIdentityServiceListRoleDefinitionsArgs()
}

func newIdentityServiceListRoleDefinitionsResult() interface{} {
	return identity_srv.NewIdentityServiceListRoleDefinitionsResult()
}

func assignRoleToUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceAssignRoleToUserArgs)
	realResult := result.(*identity_srv.IdentityServiceAssignRoleToUserResult)
	success, err := handler.(identity_srv.IdentityService).AssignRoleToUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceAssignRoleToUserArgs() interface{} {
	return identity_srv.NewIdentityServiceAssignRoleToUserArgs()
}

func newIdentityServiceAssignRoleToUserResult() interface{} {
	return identity_srv.NewIdentityServiceAssignRoleToUserResult()
}

func updateUserRoleAssignmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUpdateUserRoleAssignmentArgs)

	err := handler.(identity_srv.IdentityService).UpdateUserRoleAssignment(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceUpdateUserRoleAssignmentArgs() interface{} {
	return identity_srv.NewIdentityServiceUpdateUserRoleAssignmentArgs()
}

func newIdentityServiceUpdateUserRoleAssignmentResult() interface{} {
	return identity_srv.NewIdentityServiceUpdateUserRoleAssignmentResult()
}

func revokeRoleFromUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceRevokeRoleFromUserArgs)

	err := handler.(identity_srv.IdentityService).RevokeRoleFromUser(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceRevokeRoleFromUserArgs() interface{} {
	return identity_srv.NewIdentityServiceRevokeRoleFromUserArgs()
}

func newIdentityServiceRevokeRoleFromUserResult() interface{} {
	return identity_srv.NewIdentityServiceRevokeRoleFromUserResult()
}

func getLastUserRoleAssignmentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetLastUserRoleAssignmentArgs)
	realResult := result.(*identity_srv.IdentityServiceGetLastUserRoleAssignmentResult)
	success, err := handler.(identity_srv.IdentityService).GetLastUserRoleAssignment(ctx, realArg.UserID)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetLastUserRoleAssignmentArgs() interface{} {
	return identity_srv.NewIdentityServiceGetLastUserRoleAssignmentArgs()
}

func newIdentityServiceGetLastUserRoleAssignmentResult() interface{} {
	return identity_srv.NewIdentityServiceGetLastUserRoleAssignmentResult()
}

func listUserRoleAssignmentsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceListUserRoleAssignmentsArgs)
	realResult := result.(*identity_srv.IdentityServiceListUserRoleAssignmentsResult)
	success, err := handler.(identity_srv.IdentityService).ListUserRoleAssignments(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceListUserRoleAssignmentsArgs() interface{} {
	return identity_srv.NewIdentityServiceListUserRoleAssignmentsArgs()
}

func newIdentityServiceListUserRoleAssignmentsResult() interface{} {
	return identity_srv.NewIdentityServiceListUserRoleAssignmentsResult()
}

func getUsersByRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetUsersByRoleArgs)
	realResult := result.(*identity_srv.IdentityServiceGetUsersByRoleResult)
	success, err := handler.(identity_srv.IdentityService).GetUsersByRole(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetUsersByRoleArgs() interface{} {
	return identity_srv.NewIdentityServiceGetUsersByRoleArgs()
}

func newIdentityServiceGetUsersByRoleResult() interface{} {
	return identity_srv.NewIdentityServiceGetUsersByRoleResult()
}

func batchBindUsersToRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceBatchBindUsersToRoleArgs)
	realResult := result.(*identity_srv.IdentityServiceBatchBindUsersToRoleResult)
	success, err := handler.(identity_srv.IdentityService).BatchBindUsersToRole(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceBatchBindUsersToRoleArgs() interface{} {
	return identity_srv.NewIdentityServiceBatchBindUsersToRoleArgs()
}

func newIdentityServiceBatchBindUsersToRoleResult() interface{} {
	return identity_srv.NewIdentityServiceBatchBindUsersToRoleResult()
}

func batchGetUserRolesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceBatchGetUserRolesArgs)
	realResult := result.(*identity_srv.IdentityServiceBatchGetUserRolesResult)
	success, err := handler.(identity_srv.IdentityService).BatchGetUserRoles(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceBatchGetUserRolesArgs() interface{} {
	return identity_srv.NewIdentityServiceBatchGetUserRolesArgs()
}

func newIdentityServiceBatchGetUserRolesResult() interface{} {
	return identity_srv.NewIdentityServiceBatchGetUserRolesResult()
}

func uploadMenuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceUploadMenuArgs)

	err := handler.(identity_srv.IdentityService).UploadMenu(ctx, realArg.Req)
	if err != nil {
		return err
	}

	return nil
}
func newIdentityServiceUploadMenuArgs() interface{} {
	return identity_srv.NewIdentityServiceUploadMenuArgs()
}

func newIdentityServiceUploadMenuResult() interface{} {
	return identity_srv.NewIdentityServiceUploadMenuResult()
}

func getMenuTreeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*identity_srv.IdentityServiceGetMenuTreeArgs)
	realResult := result.(*identity_srv.IdentityServiceGetMenuTreeResult)
	success, err := handler.(identity_srv.IdentityService).GetMenuTree(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetMenuTreeArgs() interface{} {
	return identity_srv.NewIdentityServiceGetMenuTreeArgs()
}

func newIdentityServiceGetMenuTreeResult() interface{} {
	return identity_srv.NewIdentityServiceGetMenuTreeResult()
}

func configureRoleMenusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceConfigureRoleMenusArgs)
	realResult := result.(*identity_srv.IdentityServiceConfigureRoleMenusResult)
	success, err := handler.(identity_srv.IdentityService).ConfigureRoleMenus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceConfigureRoleMenusArgs() interface{} {
	return identity_srv.NewIdentityServiceConfigureRoleMenusArgs()
}

func newIdentityServiceConfigureRoleMenusResult() interface{} {
	return identity_srv.NewIdentityServiceConfigureRoleMenusResult()
}

func getRoleMenuTreeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetRoleMenuTreeArgs)
	realResult := result.(*identity_srv.IdentityServiceGetRoleMenuTreeResult)
	success, err := handler.(identity_srv.IdentityService).GetRoleMenuTree(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetRoleMenuTreeArgs() interface{} {
	return identity_srv.NewIdentityServiceGetRoleMenuTreeArgs()
}

func newIdentityServiceGetRoleMenuTreeResult() interface{} {
	return identity_srv.NewIdentityServiceGetRoleMenuTreeResult()
}

func getUserMenuTreeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetUserMenuTreeArgs)
	realResult := result.(*identity_srv.IdentityServiceGetUserMenuTreeResult)
	success, err := handler.(identity_srv.IdentityService).GetUserMenuTree(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetUserMenuTreeArgs() interface{} {
	return identity_srv.NewIdentityServiceGetUserMenuTreeArgs()
}

func newIdentityServiceGetUserMenuTreeResult() interface{} {
	return identity_srv.NewIdentityServiceGetUserMenuTreeResult()
}

func getRoleMenuPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetRoleMenuPermissionsArgs)
	realResult := result.(*identity_srv.IdentityServiceGetRoleMenuPermissionsResult)
	success, err := handler.(identity_srv.IdentityService).GetRoleMenuPermissions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetRoleMenuPermissionsArgs() interface{} {
	return identity_srv.NewIdentityServiceGetRoleMenuPermissionsArgs()
}

func newIdentityServiceGetRoleMenuPermissionsResult() interface{} {
	return identity_srv.NewIdentityServiceGetRoleMenuPermissionsResult()
}

func hasMenuPermissionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceHasMenuPermissionArgs)
	realResult := result.(*identity_srv.IdentityServiceHasMenuPermissionResult)
	success, err := handler.(identity_srv.IdentityService).HasMenuPermission(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceHasMenuPermissionArgs() interface{} {
	return identity_srv.NewIdentityServiceHasMenuPermissionArgs()
}

func newIdentityServiceHasMenuPermissionResult() interface{} {
	return identity_srv.NewIdentityServiceHasMenuPermissionResult()
}

func getUserMenuPermissionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*identity_srv.IdentityServiceGetUserMenuPermissionsArgs)
	realResult := result.(*identity_srv.IdentityServiceGetUserMenuPermissionsResult)
	success, err := handler.(identity_srv.IdentityService).GetUserMenuPermissions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newIdentityServiceGetUserMenuPermissionsArgs() interface{} {
	return identity_srv.NewIdentityServiceGetUserMenuPermissionsArgs()
}

func newIdentityServiceGetUserMenuPermissionsResult() interface{} {
	return identity_srv.NewIdentityServiceGetUserMenuPermissionsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Login(ctx context.Context, req *identity_srv.LoginRequest) (r *identity_srv.LoginResponse, err error) {
	var _args identity_srv.IdentityServiceLoginArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, req *identity_srv.ChangePasswordRequest) (err error) {
	var _args identity_srv.IdentityServiceChangePasswordArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) ResetPassword(ctx context.Context, req *identity_srv.ResetPasswordRequest) (err error) {
	var _args identity_srv.IdentityServiceResetPasswordArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceResetPasswordResult
	if err = p.c.Call(ctx, "ResetPassword", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) ForcePasswordChange(ctx context.Context, req *identity_srv.ForcePasswordChangeRequest) (err error) {
	var _args identity_srv.IdentityServiceForcePasswordChangeArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceForcePasswordChangeResult
	if err = p.c.Call(ctx, "ForcePasswordChange", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) CreateUser(ctx context.Context, req *identity_srv.CreateUserRequest) (r *identity_srv.UserProfile, err error) {
	var _args identity_srv.IdentityServiceCreateUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceCreateUserResult
	if err = p.c.Call(ctx, "CreateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUser(ctx context.Context, req *identity_srv.GetUserRequest) (r *identity_srv.UserProfile, err error) {
	var _args identity_srv.IdentityServiceGetUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetUserResult
	if err = p.c.Call(ctx, "GetUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUser(ctx context.Context, req *identity_srv.UpdateUserRequest) (r *identity_srv.UserProfile, err error) {
	var _args identity_srv.IdentityServiceUpdateUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUser(ctx context.Context, req *identity_srv.DeleteUserRequest) (err error) {
	var _args identity_srv.IdentityServiceDeleteUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceDeleteUserResult
	if err = p.c.Call(ctx, "DeleteUser", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) ListUsers(ctx context.Context, req *identity_srv.ListUsersRequest) (r *identity_srv.ListUsersResponse, err error) {
	var _args identity_srv.IdentityServiceListUsersArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceListUsersResult
	if err = p.c.Call(ctx, "ListUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SearchUsers(ctx context.Context, req *identity_srv.SearchUsersRequest) (r *identity_srv.SearchUsersResponse, err error) {
	var _args identity_srv.IdentityServiceSearchUsersArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceSearchUsersResult
	if err = p.c.Call(ctx, "SearchUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeUserStatus(ctx context.Context, req *identity_srv.ChangeUserStatusRequest) (err error) {
	var _args identity_srv.IdentityServiceChangeUserStatusArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceChangeUserStatusResult
	if err = p.c.Call(ctx, "ChangeUserStatus", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) UnlockUser(ctx context.Context, req *identity_srv.UnlockUserRequest) (err error) {
	var _args identity_srv.IdentityServiceUnlockUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUnlockUserResult
	if err = p.c.Call(ctx, "UnlockUser", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) CreateOrganization(ctx context.Context, req *identity_srv.CreateOrganizationRequest) (r *identity_srv.Organization, err error) {
	var _args identity_srv.IdentityServiceCreateOrganizationArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceCreateOrganizationResult
	if err = p.c.Call(ctx, "CreateOrganization", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrganization(ctx context.Context, req *identity_srv.GetOrganizationRequest) (r *identity_srv.Organization, err error) {
	var _args identity_srv.IdentityServiceGetOrganizationArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetOrganizationResult
	if err = p.c.Call(ctx, "GetOrganization", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateOrganization(ctx context.Context, req *identity_srv.UpdateOrganizationRequest) (r *identity_srv.Organization, err error) {
	var _args identity_srv.IdentityServiceUpdateOrganizationArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateOrganizationResult
	if err = p.c.Call(ctx, "UpdateOrganization", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteOrganization(ctx context.Context, organizationID core.UUID) (err error) {
	var _args identity_srv.IdentityServiceDeleteOrganizationArgs
	_args.OrganizationID = organizationID
	var _result identity_srv.IdentityServiceDeleteOrganizationResult
	if err = p.c.Call(ctx, "DeleteOrganization", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) ListOrganizations(ctx context.Context, req *identity_srv.ListOrganizationsRequest) (r *identity_srv.ListOrganizationsResponse, err error) {
	var _args identity_srv.IdentityServiceListOrganizationsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceListOrganizationsResult
	if err = p.c.Call(ctx, "ListOrganizations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddMembership(ctx context.Context, req *identity_srv.AddMembershipRequest) (r *identity_srv.UserMembership, err error) {
	var _args identity_srv.IdentityServiceAddMembershipArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceAddMembershipResult
	if err = p.c.Call(ctx, "AddMembership", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateMembership(ctx context.Context, req *identity_srv.UpdateMembershipRequest) (r *identity_srv.UserMembership, err error) {
	var _args identity_srv.IdentityServiceUpdateMembershipArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateMembershipResult
	if err = p.c.Call(ctx, "UpdateMembership", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RemoveMembership(ctx context.Context, membershipID core.UUID) (err error) {
	var _args identity_srv.IdentityServiceRemoveMembershipArgs
	_args.MembershipID = membershipID
	var _result identity_srv.IdentityServiceRemoveMembershipResult
	if err = p.c.Call(ctx, "RemoveMembership", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) GetMembership(ctx context.Context, membershipID core.UUID) (r *identity_srv.UserMembership, err error) {
	var _args identity_srv.IdentityServiceGetMembershipArgs
	_args.MembershipID = membershipID
	var _result identity_srv.IdentityServiceGetMembershipResult
	if err = p.c.Call(ctx, "GetMembership", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserMemberships(ctx context.Context, req *identity_srv.GetUserMembershipsRequest) (r *identity_srv.GetUserMembershipsResponse, err error) {
	var _args identity_srv.IdentityServiceGetUserMembershipsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetUserMembershipsResult
	if err = p.c.Call(ctx, "GetUserMemberships", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPrimaryMembership(ctx context.Context, userID core.UUID) (r *identity_srv.UserMembership, err error) {
	var _args identity_srv.IdentityServiceGetPrimaryMembershipArgs
	_args.UserID = userID
	var _result identity_srv.IdentityServiceGetPrimaryMembershipResult
	if err = p.c.Call(ctx, "GetPrimaryMembership", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CheckMembership(ctx context.Context, req *identity_srv.CheckMembershipRequest) (r bool, err error) {
	var _args identity_srv.IdentityServiceCheckMembershipArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceCheckMembershipResult
	if err = p.c.Call(ctx, "CheckMembership", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateDepartment(ctx context.Context, req *identity_srv.CreateDepartmentRequest) (r *identity_srv.Department, err error) {
	var _args identity_srv.IdentityServiceCreateDepartmentArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceCreateDepartmentResult
	if err = p.c.Call(ctx, "CreateDepartment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDepartment(ctx context.Context, req *identity_srv.GetDepartmentRequest) (r *identity_srv.Department, err error) {
	var _args identity_srv.IdentityServiceGetDepartmentArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetDepartmentResult
	if err = p.c.Call(ctx, "GetDepartment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateDepartment(ctx context.Context, req *identity_srv.UpdateDepartmentRequest) (r *identity_srv.Department, err error) {
	var _args identity_srv.IdentityServiceUpdateDepartmentArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateDepartmentResult
	if err = p.c.Call(ctx, "UpdateDepartment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteDepartment(ctx context.Context, departmentID core.UUID) (err error) {
	var _args identity_srv.IdentityServiceDeleteDepartmentArgs
	_args.DepartmentID = departmentID
	var _result identity_srv.IdentityServiceDeleteDepartmentResult
	if err = p.c.Call(ctx, "DeleteDepartment", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) GetOrganizationDepartments(ctx context.Context, req *identity_srv.GetOrganizationDepartmentsRequest) (r *identity_srv.GetOrganizationDepartmentsResponse, err error) {
	var _args identity_srv.IdentityServiceGetOrganizationDepartmentsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetOrganizationDepartmentsResult
	if err = p.c.Call(ctx, "GetOrganizationDepartments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadTemporaryLogo(ctx context.Context, req *identity_srv.UploadTemporaryLogoRequest) (r *identity_srv.OrganizationLogo, err error) {
	var _args identity_srv.IdentityServiceUploadTemporaryLogoArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUploadTemporaryLogoResult
	if err = p.c.Call(ctx, "UploadTemporaryLogo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrganizationLogo(ctx context.Context, req *identity_srv.GetOrganizationLogoRequest) (r *identity_srv.OrganizationLogo, err error) {
	var _args identity_srv.IdentityServiceGetOrganizationLogoArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetOrganizationLogoResult
	if err = p.c.Call(ctx, "GetOrganizationLogo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteOrganizationLogo(ctx context.Context, req *identity_srv.DeleteOrganizationLogoRequest) (err error) {
	var _args identity_srv.IdentityServiceDeleteOrganizationLogoArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceDeleteOrganizationLogoResult
	if err = p.c.Call(ctx, "DeleteOrganizationLogo", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) BindLogoToOrganization(ctx context.Context, req *identity_srv.BindLogoToOrganizationRequest) (r *identity_srv.OrganizationLogo, err error) {
	var _args identity_srv.IdentityServiceBindLogoToOrganizationArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceBindLogoToOrganizationResult
	if err = p.c.Call(ctx, "BindLogoToOrganization", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionCreateRequest) (r *identity_srv.RoleDefinition, err error) {
	var _args identity_srv.IdentityServiceCreateRoleDefinitionArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceCreateRoleDefinitionResult
	if err = p.c.Call(ctx, "CreateRoleDefinition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateRoleDefinition(ctx context.Context, req *identity_srv.RoleDefinitionUpdateRequest) (r *identity_srv.RoleDefinition, err error) {
	var _args identity_srv.IdentityServiceUpdateRoleDefinitionArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateRoleDefinitionResult
	if err = p.c.Call(ctx, "UpdateRoleDefinition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteRoleDefinition(ctx context.Context, roleID core.UUID) (err error) {
	var _args identity_srv.IdentityServiceDeleteRoleDefinitionArgs
	_args.RoleID = roleID
	var _result identity_srv.IdentityServiceDeleteRoleDefinitionResult
	if err = p.c.Call(ctx, "DeleteRoleDefinition", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) GetRoleDefinition(ctx context.Context, roleID core.UUID) (r *identity_srv.RoleDefinition, err error) {
	var _args identity_srv.IdentityServiceGetRoleDefinitionArgs
	_args.RoleID = roleID
	var _result identity_srv.IdentityServiceGetRoleDefinitionResult
	if err = p.c.Call(ctx, "GetRoleDefinition", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListRoleDefinitions(ctx context.Context, req *identity_srv.RoleDefinitionQueryRequest) (r *identity_srv.RoleDefinitionListResponse, err error) {
	var _args identity_srv.IdentityServiceListRoleDefinitionsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceListRoleDefinitionsResult
	if err = p.c.Call(ctx, "ListRoleDefinitions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AssignRoleToUser(ctx context.Context, req *identity_srv.AssignRoleToUserRequest) (r *identity_srv.UserRoleAssignmentResponse, err error) {
	var _args identity_srv.IdentityServiceAssignRoleToUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceAssignRoleToUserResult
	if err = p.c.Call(ctx, "AssignRoleToUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserRoleAssignment(ctx context.Context, req *identity_srv.UpdateUserRoleAssignmentRequest) (err error) {
	var _args identity_srv.IdentityServiceUpdateUserRoleAssignmentArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUpdateUserRoleAssignmentResult
	if err = p.c.Call(ctx, "UpdateUserRoleAssignment", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) RevokeRoleFromUser(ctx context.Context, req *identity_srv.RevokeRoleFromUserRequest) (err error) {
	var _args identity_srv.IdentityServiceRevokeRoleFromUserArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceRevokeRoleFromUserResult
	if err = p.c.Call(ctx, "RevokeRoleFromUser", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) GetLastUserRoleAssignment(ctx context.Context, userID core.UUID) (r *identity_srv.UserRoleAssignment, err error) {
	var _args identity_srv.IdentityServiceGetLastUserRoleAssignmentArgs
	_args.UserID = userID
	var _result identity_srv.IdentityServiceGetLastUserRoleAssignmentResult
	if err = p.c.Call(ctx, "GetLastUserRoleAssignment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListUserRoleAssignments(ctx context.Context, req *identity_srv.UserRoleQueryRequest) (r *identity_srv.UserRoleListResponse, err error) {
	var _args identity_srv.IdentityServiceListUserRoleAssignmentsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceListUserRoleAssignmentsResult
	if err = p.c.Call(ctx, "ListUserRoleAssignments", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUsersByRole(ctx context.Context, req *identity_srv.GetUsersByRoleRequest) (r *identity_srv.GetUsersByRoleResponse, err error) {
	var _args identity_srv.IdentityServiceGetUsersByRoleArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetUsersByRoleResult
	if err = p.c.Call(ctx, "GetUsersByRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchBindUsersToRole(ctx context.Context, req *identity_srv.BatchBindUsersToRoleRequest) (r *identity_srv.BatchBindUsersToRoleResponse, err error) {
	var _args identity_srv.IdentityServiceBatchBindUsersToRoleArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceBatchBindUsersToRoleResult
	if err = p.c.Call(ctx, "BatchBindUsersToRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BatchGetUserRoles(ctx context.Context, req *identity_srv.BatchGetUserRolesRequest) (r *identity_srv.BatchGetUserRolesResponse, err error) {
	var _args identity_srv.IdentityServiceBatchGetUserRolesArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceBatchGetUserRolesResult
	if err = p.c.Call(ctx, "BatchGetUserRoles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UploadMenu(ctx context.Context, req *identity_srv.UploadMenuRequest) (err error) {
	var _args identity_srv.IdentityServiceUploadMenuArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceUploadMenuResult
	if err = p.c.Call(ctx, "UploadMenu", &_args, &_result); err != nil {
		return
	}
	return nil
}

func (p *kClient) GetMenuTree(ctx context.Context) (r *identity_srv.GetMenuTreeResponse, err error) {
	var _args identity_srv.IdentityServiceGetMenuTreeArgs
	var _result identity_srv.IdentityServiceGetMenuTreeResult
	if err = p.c.Call(ctx, "GetMenuTree", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ConfigureRoleMenus(ctx context.Context, req *identity_srv.ConfigureRoleMenusRequest) (r *identity_srv.ConfigureRoleMenusResponse, err error) {
	var _args identity_srv.IdentityServiceConfigureRoleMenusArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceConfigureRoleMenusResult
	if err = p.c.Call(ctx, "ConfigureRoleMenus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRoleMenuTree(ctx context.Context, req *identity_srv.GetRoleMenuTreeRequest) (r *identity_srv.GetRoleMenuTreeResponse, err error) {
	var _args identity_srv.IdentityServiceGetRoleMenuTreeArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetRoleMenuTreeResult
	if err = p.c.Call(ctx, "GetRoleMenuTree", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserMenuTree(ctx context.Context, req *identity_srv.GetUserMenuTreeRequest) (r *identity_srv.GetUserMenuTreeResponse, err error) {
	var _args identity_srv.IdentityServiceGetUserMenuTreeArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetUserMenuTreeResult
	if err = p.c.Call(ctx, "GetUserMenuTree", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetRoleMenuPermissions(ctx context.Context, req *identity_srv.GetRoleMenuPermissionsRequest) (r *identity_srv.GetRoleMenuPermissionsResponse, err error) {
	var _args identity_srv.IdentityServiceGetRoleMenuPermissionsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetRoleMenuPermissionsResult
	if err = p.c.Call(ctx, "GetRoleMenuPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HasMenuPermission(ctx context.Context, req *identity_srv.HasMenuPermissionRequest) (r *identity_srv.HasMenuPermissionResponse, err error) {
	var _args identity_srv.IdentityServiceHasMenuPermissionArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceHasMenuPermissionResult
	if err = p.c.Call(ctx, "HasMenuPermission", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserMenuPermissions(ctx context.Context, req *identity_srv.GetUserMenuPermissionsRequest) (r *identity_srv.GetUserMenuPermissionsResponse, err error) {
	var _args identity_srv.IdentityServiceGetUserMenuPermissionsArgs
	_args.Req = req
	var _result identity_srv.IdentityServiceGetUserMenuPermissionsResult
	if err = p.c.Call(ctx, "GetUserMenuPermissions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
