// Code generated by Kitex v0.15.2. DO NOT EDIT.
package identityservice

import (
	server "github.com/cloudwego/kitex/server"
	identity_srv "github.com/masonsxu/cloudwego-scaffold/rpc/identity-srv/kitex_gen/identity_srv"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler identity_srv.IdentityService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler identity_srv.IdentityService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
