// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/hertz-contrib/logger/zerolog"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/application/assembler/identity"
	"github.com/masonsxu/cloudwego-scaffold/gateway/internal/application/assembler/permission"
)

// Injectors from wire.go:

// InitializeService 初始化服务容器
// Wire会自动生成依赖注入代码
func InitializeService() (*ServiceContainer, error) {
	configuration := ProvideConfig()
	logger := ProvideLogger(configuration)
	identityClient := ProvideIdentityClient(logger)
	iAuthAssembler := identity.NewAuthAssembler()
	iUserAssembler := identity.NewUserAssembler()
	iOrgAssembler := identity.NewOrgAssembler()
	iDepartmentAssembler := identity.NewDepartmentAssembler()
	iMembershipAssembler := identity.NewMembershipAssembler()
	iLogoAssembler := identity.NewLogoAssembler()
	assembler := identity.NewIdentityAggregateAssembler(iAuthAssembler, iUserAssembler, iOrgAssembler, iDepartmentAssembler, iMembershipAssembler, iLogoAssembler)
	authService := ProvideAuthService(identityClient, assembler, logger)
	userService := ProvideUserService(identityClient, assembler, logger)
	membershipService := ProvideMembershipService(identityClient, assembler, logger)
	organizationService := ProvideOrganizationService(identityClient, assembler, logger)
	departmentService := ProvideDepartmentService(identityClient, assembler, logger)
	logoService := ProvideLogoService(identityClient, assembler, logger)
	service := ProvideIdentityService(authService, userService, membershipService, organizationService, departmentService, logoService)
	iPermissionAssembler := permission.NewPermissionAssembler()
	iRoleAssembler := permission.NewRoleAssembler(iPermissionAssembler)
	iUserRoleAssembler := permission.NewUserRoleAssembler()
	iMenuAssembler := permission.NewMenuAssembler()
	permissionAssembler := permission.NewPermissionAggregateAssembler(iRoleAssembler, iPermissionAssembler, iUserRoleAssembler, iMenuAssembler)
	roleDefinitionService := ProvideRoleDefinitionService(identityClient, permissionAssembler, logger)
	userRoleAssignmentService := ProvideUserRoleAssignmentService(identityClient, permissionAssembler, logger)
	menuService := ProvideMenuService(identityClient, permissionAssembler, logger)
	permissionService := ProvidePermissionService(roleDefinitionService, userRoleAssignmentService, menuService)
	serviceContainer := NewServiceContainer(service, permissionService)
	return serviceContainer, nil
}

// InitializeMiddleware 初始化中间件容器
// Wire会自动生成依赖注入代码
func InitializeMiddleware() (*MiddlewareContainer, error) {
	configuration := ProvideConfig()
	logger := ProvideLogger(configuration)
	traceMiddlewareService := ProvideTraceMiddleware(logger)
	corsMiddlewareService := ProvideCORSMiddleware(configuration, logger)
	errorHandlerMiddlewareService := ProvideErrorHandlerMiddleware(configuration, logger)
	identityClient := ProvideIdentityClient(logger)
	iAuthAssembler := identity.NewAuthAssembler()
	iUserAssembler := identity.NewUserAssembler()
	iOrgAssembler := identity.NewOrgAssembler()
	iDepartmentAssembler := identity.NewDepartmentAssembler()
	iMembershipAssembler := identity.NewMembershipAssembler()
	iLogoAssembler := identity.NewLogoAssembler()
	assembler := identity.NewIdentityAggregateAssembler(iAuthAssembler, iUserAssembler, iOrgAssembler, iDepartmentAssembler, iMembershipAssembler, iLogoAssembler)
	authService := ProvideAuthService(identityClient, assembler, logger)
	userService := ProvideUserService(identityClient, assembler, logger)
	membershipService := ProvideMembershipService(identityClient, assembler, logger)
	organizationService := ProvideOrganizationService(identityClient, assembler, logger)
	departmentService := ProvideDepartmentService(identityClient, assembler, logger)
	logoService := ProvideLogoService(identityClient, assembler, logger)
	service := ProvideIdentityService(authService, userService, membershipService, organizationService, departmentService, logoService)
	jwtConfig := ProvideJWTConfig(configuration)
	redisConfig := ProvideRedisConfig(configuration)
	client, err := ProvideRedisClient(redisConfig)
	if err != nil {
		return nil, err
	}
	tokenCacheService := ProvideTokenCache(client, logger)
	jwtMiddlewareService := ProvideJWTMiddleware(service, jwtConfig, tokenCacheService, logger)
	middlewareContainer := NewMiddlewareContainer(traceMiddlewareService, corsMiddlewareService, errorHandlerMiddlewareService, jwtMiddlewareService)
	return middlewareContainer, nil
}

// InitializeLogger 初始化日志服务
// 提供给外部模块使用的日志实例
func InitializeLogger() *zerolog.Logger {
	configuration := ProvideConfig()
	logger := ProvideLogger(configuration)
	return logger
}

// wire.go:

// AllSet 所有依赖注入集合
// 按照分层架构组织：基础设施层 -> 应用层 -> 领域层 -> 中间件层
var AllSet = wire.NewSet(

	InfrastructureSet,

	ApplicationSet,

	DomainServiceSet,

	MiddlewareSet,

	NewServiceContainer,
)
