// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package http_base

import (
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/masonsxu/cloudwego-scaffold/gateway/biz/model/core"
)

// =================================================================
//                       JWT 相关数据结构
// =================================================================
/**
 * JWT 令牌声明（Claims）信息
 * 这些信息将直接嵌入到 JWT Token 中
 */
type JWTClaimsDTO struct {
	// 用户ID
	UserProfileID *string `thrift:"userProfileID,1,optional" json:"user_profile_id,omitempty" form:"user_profile_id" query:"user_profile_id"`
	// 用户名
	Username *string `thrift:"username,2,optional" json:"username,omitempty" form:"username" query:"username"`
	// 用户状态
	Status *core.UserStatus `thrift:"status,3,optional,UserStatus" json:"status,omitempty" form:"status" query:"status"`
	// 角色ID
	RoleID *string `thrift:"roleID,4,optional" json:"role_id,omitempty" form:"role_id" query:"role_id"`
	// 所属组织ID
	OrganizationID *string `thrift:"organizationID,5,optional" json:"organization_id,omitempty" form:"organization_id" query:"organization_id"`
	// 所属部门ID
	DepartmentID *string `thrift:"departmentID,6,optional" json:"department_id,omitempty" form:"department_id" query:"department_id"`
	// 权限
	Permission *string `thrift:"permission,7,optional" json:"permission,omitempty" form:"permission" query:"permission"`
	// 过期时间（Unix时间戳）
	Exp *int64 `thrift:"exp,8,optional" json:"exp,omitempty" form:"exp" query:"exp"`
	// 签发时间（Unix时间戳）
	Iat *int64 `thrift:"iat,9,optional" json:"iat,omitempty" form:"iat" query:"iat"`
}

func NewJWTClaimsDTO() *JWTClaimsDTO {
	return &JWTClaimsDTO{}
}

func (p *JWTClaimsDTO) InitDefault() {
}

var JWTClaimsDTO_UserProfileID_DEFAULT string

func (p *JWTClaimsDTO) GetUserProfileID() (v string) {
	if !p.IsSetUserProfileID() {
		return JWTClaimsDTO_UserProfileID_DEFAULT
	}
	return *p.UserProfileID
}

var JWTClaimsDTO_Username_DEFAULT string

func (p *JWTClaimsDTO) GetUsername() (v string) {
	if !p.IsSetUsername() {
		return JWTClaimsDTO_Username_DEFAULT
	}
	return *p.Username
}

var JWTClaimsDTO_Status_DEFAULT core.UserStatus

func (p *JWTClaimsDTO) GetStatus() (v core.UserStatus) {
	if !p.IsSetStatus() {
		return JWTClaimsDTO_Status_DEFAULT
	}
	return *p.Status
}

var JWTClaimsDTO_RoleID_DEFAULT string

func (p *JWTClaimsDTO) GetRoleID() (v string) {
	if !p.IsSetRoleID() {
		return JWTClaimsDTO_RoleID_DEFAULT
	}
	return *p.RoleID
}

var JWTClaimsDTO_OrganizationID_DEFAULT string

func (p *JWTClaimsDTO) GetOrganizationID() (v string) {
	if !p.IsSetOrganizationID() {
		return JWTClaimsDTO_OrganizationID_DEFAULT
	}
	return *p.OrganizationID
}

var JWTClaimsDTO_DepartmentID_DEFAULT string

func (p *JWTClaimsDTO) GetDepartmentID() (v string) {
	if !p.IsSetDepartmentID() {
		return JWTClaimsDTO_DepartmentID_DEFAULT
	}
	return *p.DepartmentID
}

var JWTClaimsDTO_Permission_DEFAULT string

func (p *JWTClaimsDTO) GetPermission() (v string) {
	if !p.IsSetPermission() {
		return JWTClaimsDTO_Permission_DEFAULT
	}
	return *p.Permission
}

var JWTClaimsDTO_Exp_DEFAULT int64

func (p *JWTClaimsDTO) GetExp() (v int64) {
	if !p.IsSetExp() {
		return JWTClaimsDTO_Exp_DEFAULT
	}
	return *p.Exp
}

var JWTClaimsDTO_Iat_DEFAULT int64

func (p *JWTClaimsDTO) GetIat() (v int64) {
	if !p.IsSetIat() {
		return JWTClaimsDTO_Iat_DEFAULT
	}
	return *p.Iat
}

var fieldIDToName_JWTClaimsDTO = map[int16]string{
	1: "userProfileID",
	2: "username",
	3: "status",
	4: "roleID",
	5: "organizationID",
	6: "departmentID",
	7: "permission",
	8: "exp",
	9: "iat",
}

func (p *JWTClaimsDTO) IsSetUserProfileID() bool {
	return p.UserProfileID != nil
}

func (p *JWTClaimsDTO) IsSetUsername() bool {
	return p.Username != nil
}

func (p *JWTClaimsDTO) IsSetStatus() bool {
	return p.Status != nil
}

func (p *JWTClaimsDTO) IsSetRoleID() bool {
	return p.RoleID != nil
}

func (p *JWTClaimsDTO) IsSetOrganizationID() bool {
	return p.OrganizationID != nil
}

func (p *JWTClaimsDTO) IsSetDepartmentID() bool {
	return p.DepartmentID != nil
}

func (p *JWTClaimsDTO) IsSetPermission() bool {
	return p.Permission != nil
}

func (p *JWTClaimsDTO) IsSetExp() bool {
	return p.Exp != nil
}

func (p *JWTClaimsDTO) IsSetIat() bool {
	return p.Iat != nil
}

func (p *JWTClaimsDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_JWTClaimsDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *JWTClaimsDTO) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UserProfileID = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Username = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField3(iprot thrift.TProtocol) error {

	var _field *core.UserStatus
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		tmp := core.UserStatus(v)
		_field = &tmp
	}
	p.Status = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.RoleID = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.OrganizationID = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField6(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.DepartmentID = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField7(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Permission = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField8(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Exp = _field
	return nil
}
func (p *JWTClaimsDTO) ReadField9(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Iat = _field
	return nil
}

func (p *JWTClaimsDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("JWTClaimsDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetUserProfileID() {
		if err = oprot.WriteFieldBegin("userProfileID", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UserProfileID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetUsername() {
		if err = oprot.WriteFieldBegin("username", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Username); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetStatus() {
		if err = oprot.WriteFieldBegin("status", thrift.I32, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(int32(*p.Status)); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetRoleID() {
		if err = oprot.WriteFieldBegin("roleID", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.RoleID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetOrganizationID() {
		if err = oprot.WriteFieldBegin("organizationID", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.OrganizationID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetDepartmentID() {
		if err = oprot.WriteFieldBegin("departmentID", thrift.STRING, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.DepartmentID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetPermission() {
		if err = oprot.WriteFieldBegin("permission", thrift.STRING, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Permission); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetExp() {
		if err = oprot.WriteFieldBegin("exp", thrift.I64, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.Exp); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *JWTClaimsDTO) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetIat() {
		if err = oprot.WriteFieldBegin("iat", thrift.I64, 9); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.Iat); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}

func (p *JWTClaimsDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JWTClaimsDTO(%+v)", *p)

}

/**
 * 令牌信息DTO
 */
type TokenInfoDTO struct {
	// 访问令牌
	AccessToken *string `thrift:"accessToken,1,optional" json:"access_token,omitempty" form:"access_token" query:"access_token"`
	// 访问令牌过期时间（秒）
	ExpiresIn *int64 `thrift:"expiresIn,2,optional" json:"expires_in,omitempty" form:"expires_in" query:"expires_in"`
	// 令牌类型（通常是"Bearer"）
	TokenType *string `thrift:"tokenType,3,optional" json:"token_type,omitempty" form:"token_type" query:"token_type"`
}

func NewTokenInfoDTO() *TokenInfoDTO {
	return &TokenInfoDTO{}
}

func (p *TokenInfoDTO) InitDefault() {
}

var TokenInfoDTO_AccessToken_DEFAULT string

func (p *TokenInfoDTO) GetAccessToken() (v string) {
	if !p.IsSetAccessToken() {
		return TokenInfoDTO_AccessToken_DEFAULT
	}
	return *p.AccessToken
}

var TokenInfoDTO_ExpiresIn_DEFAULT int64

func (p *TokenInfoDTO) GetExpiresIn() (v int64) {
	if !p.IsSetExpiresIn() {
		return TokenInfoDTO_ExpiresIn_DEFAULT
	}
	return *p.ExpiresIn
}

var TokenInfoDTO_TokenType_DEFAULT string

func (p *TokenInfoDTO) GetTokenType() (v string) {
	if !p.IsSetTokenType() {
		return TokenInfoDTO_TokenType_DEFAULT
	}
	return *p.TokenType
}

var fieldIDToName_TokenInfoDTO = map[int16]string{
	1: "accessToken",
	2: "expiresIn",
	3: "tokenType",
}

func (p *TokenInfoDTO) IsSetAccessToken() bool {
	return p.AccessToken != nil
}

func (p *TokenInfoDTO) IsSetExpiresIn() bool {
	return p.ExpiresIn != nil
}

func (p *TokenInfoDTO) IsSetTokenType() bool {
	return p.TokenType != nil
}

func (p *TokenInfoDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_TokenInfoDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *TokenInfoDTO) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.AccessToken = _field
	return nil
}
func (p *TokenInfoDTO) ReadField2(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ExpiresIn = _field
	return nil
}
func (p *TokenInfoDTO) ReadField3(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.TokenType = _field
	return nil
}

func (p *TokenInfoDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("TokenInfoDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *TokenInfoDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetAccessToken() {
		if err = oprot.WriteFieldBegin("accessToken", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.AccessToken); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *TokenInfoDTO) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetExpiresIn() {
		if err = oprot.WriteFieldBegin("expiresIn", thrift.I64, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.ExpiresIn); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *TokenInfoDTO) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetTokenType() {
		if err = oprot.WriteFieldBegin("tokenType", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.TokenType); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *TokenInfoDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TokenInfoDTO(%+v)", *p)

}

// =================================================================
//                      通用请求/响应结构
// =================================================================
/**
 * API Gateway 统一响应基类
 * 针对 REST API 优化的响应结构
 */
type BaseResponseDTO struct {
	// 错误码，0表示成功
	Code int32 `thrift:"code,1,required" json:"code" form:"code,required" query:"code,required"`
	// 人类可读的提示信息
	Message string `thrift:"message,2,required" json:"message" form:"message,required" query:"message,required"`
	// 本次请求的唯一ID（用于追踪）
	RequestID string `thrift:"request_id,3,required" json:"request_id" form:"request_id,required" query:"request_id,required"`
	// 用于链路追踪的ID
	TraceID string `thrift:"trace_id,4,required" json:"trace_id" form:"trace_id,required" query:"trace_id,required"`
	// 服务器响应时间戳 (ms)
	Timestamp core.TimestampMS `thrift:"timestamp,5,required" json:"timestamp" form:"timestamp,required" query:"timestamp,required"`
	// 其他元数据
	Metadata map[string]string `thrift:"metadata,6,optional" json:"metadata,omitempty" form:"metadata" query:"metadata"`
}

func NewBaseResponseDTO() *BaseResponseDTO {
	return &BaseResponseDTO{
		Code:    0,
		Message: "success",
	}
}

func (p *BaseResponseDTO) InitDefault() {
	p.Code = 0
	p.Message = "success"
}

func (p *BaseResponseDTO) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResponseDTO) GetMessage() (v string) {
	return p.Message
}

func (p *BaseResponseDTO) GetRequestID() (v string) {
	return p.RequestID
}

func (p *BaseResponseDTO) GetTraceID() (v string) {
	return p.TraceID
}

func (p *BaseResponseDTO) GetTimestamp() (v core.TimestampMS) {
	return p.Timestamp
}

var BaseResponseDTO_Metadata_DEFAULT map[string]string

func (p *BaseResponseDTO) GetMetadata() (v map[string]string) {
	if !p.IsSetMetadata() {
		return BaseResponseDTO_Metadata_DEFAULT
	}
	return p.Metadata
}

var fieldIDToName_BaseResponseDTO = map[int16]string{
	1: "code",
	2: "message",
	3: "request_id",
	4: "trace_id",
	5: "timestamp",
	6: "metadata",
}

func (p *BaseResponseDTO) IsSetMetadata() bool {
	return p.Metadata != nil
}

func (p *BaseResponseDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetCode bool = false
	var issetMessage bool = false
	var issetRequestID bool = false
	var issetTraceID bool = false
	var issetTimestamp bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetCode = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetMessage = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetRequestID = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetTraceID = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
				issetTimestamp = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetCode {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetMessage {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetRequestID {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetTraceID {
		fieldId = 4
		goto RequiredFieldNotSetError
	}

	if !issetTimestamp {
		fieldId = 5
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_BaseResponseDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_BaseResponseDTO[fieldId]))
}

func (p *BaseResponseDTO) ReadField1(iprot thrift.TProtocol) error {

	var _field int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Code = _field
	return nil
}
func (p *BaseResponseDTO) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Message = _field
	return nil
}
func (p *BaseResponseDTO) ReadField3(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.RequestID = _field
	return nil
}
func (p *BaseResponseDTO) ReadField4(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.TraceID = _field
	return nil
}
func (p *BaseResponseDTO) ReadField5(iprot thrift.TProtocol) error {

	var _field core.TimestampMS
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Timestamp = _field
	return nil
}
func (p *BaseResponseDTO) ReadField6(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	_field := make(map[string]string, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}

		var _val string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_val = v
		}

		_field[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	p.Metadata = _field
	return nil
}

func (p *BaseResponseDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("BaseResponseDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *BaseResponseDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("code", thrift.I32, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(p.Code); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *BaseResponseDTO) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("message", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Message); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *BaseResponseDTO) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("request_id", thrift.STRING, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.RequestID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *BaseResponseDTO) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("trace_id", thrift.STRING, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.TraceID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *BaseResponseDTO) writeField5(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("timestamp", thrift.I64, 5); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Timestamp); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *BaseResponseDTO) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetMetadata() {
		if err = oprot.WriteFieldBegin("metadata", thrift.MAP, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.Metadata)); err != nil {
			return err
		}
		for k, v := range p.Metadata {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *BaseResponseDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResponseDTO(%+v)", *p)

}

/**
 * 通用操作状态响应DTO
 * 适用于删除、更新等只需返回操作状态的接口
 * 只保留基础响应信息以确保API响应格式统一
 */
type OperationStatusResponseDTO struct {
	// 基础响应信息
	BaseResp *BaseResponseDTO `thrift:"base_resp,1,required" json:"base_resp" form:"base_resp,required" query:"base_resp,required"`
}

func NewOperationStatusResponseDTO() *OperationStatusResponseDTO {
	return &OperationStatusResponseDTO{}
}

func (p *OperationStatusResponseDTO) InitDefault() {
}

var OperationStatusResponseDTO_BaseResp_DEFAULT *BaseResponseDTO

func (p *OperationStatusResponseDTO) GetBaseResp() (v *BaseResponseDTO) {
	if !p.IsSetBaseResp() {
		return OperationStatusResponseDTO_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var fieldIDToName_OperationStatusResponseDTO = map[int16]string{
	1: "base_resp",
}

func (p *OperationStatusResponseDTO) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *OperationStatusResponseDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBaseResp bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBaseResp = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBaseResp {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_OperationStatusResponseDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_OperationStatusResponseDTO[fieldId]))
}

func (p *OperationStatusResponseDTO) ReadField1(iprot thrift.TProtocol) error {
	_field := NewBaseResponseDTO()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.BaseResp = _field
	return nil
}

func (p *OperationStatusResponseDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("OperationStatusResponseDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *OperationStatusResponseDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("base_resp", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResp.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *OperationStatusResponseDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OperationStatusResponseDTO(%+v)", *p)

}

/**
 * 分页请求
 * 针对 REST API 优化的分页参数
 */
type PageRequestDTO struct {
	// 分页参数
	Page int32 `thrift:"page,1,optional" json:"page,omitempty" form:"page" query:"page" vd:"!isset(FetchAll) || *(FetchAll)$ || $>0" `
	// 每页数量
	Limit int32 `thrift:"limit,2,optional" json:"limit,omitempty" form:"limit" query:"limit" vd:"!isset(FetchAll) || *(FetchAll)$ || ($>0 && $<=200)" `
	// 搜索与过滤
	Search *string `thrift:"search,3,optional" json:"search,omitempty" form:"search" query:"search"`
	// 字段级过滤
	Filter map[string]string `thrift:"filter,4,optional" json:"filter,omitempty" form:"filter" query:"filter"`
	// 排序
	Sort *string `thrift:"sort,5,optional" json:"sort,omitempty" form:"sort" query:"sort"`
	// 字段选择（可选增强）
	Fields []string `thrift:"fields,6,optional,list<string>" json:"fields,omitempty" form:"fields" query:"fields"`
	// 是否返回总数
	IncludeTotal *bool `thrift:"include_total,7,optional" json:"include_total,omitempty" form:"include_total" query:"include_total"`
	// 是否获取所有数据（不分页）
	FetchAll *bool `thrift:"fetch_all,8,optional" json:"fetch_all,omitempty" form:"fetch_all" query:"fetch_all"`
}

func NewPageRequestDTO() *PageRequestDTO {
	return &PageRequestDTO{
		Page:  1,
		Limit: 20,
	}
}

func (p *PageRequestDTO) InitDefault() {
	p.Page = 1
	p.Limit = 20
}

var PageRequestDTO_Page_DEFAULT int32 = 1

func (p *PageRequestDTO) GetPage() (v int32) {
	if !p.IsSetPage() {
		return PageRequestDTO_Page_DEFAULT
	}
	return p.Page
}

var PageRequestDTO_Limit_DEFAULT int32 = 20

func (p *PageRequestDTO) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return PageRequestDTO_Limit_DEFAULT
	}
	return p.Limit
}

var PageRequestDTO_Search_DEFAULT string

func (p *PageRequestDTO) GetSearch() (v string) {
	if !p.IsSetSearch() {
		return PageRequestDTO_Search_DEFAULT
	}
	return *p.Search
}

var PageRequestDTO_Filter_DEFAULT map[string]string

func (p *PageRequestDTO) GetFilter() (v map[string]string) {
	if !p.IsSetFilter() {
		return PageRequestDTO_Filter_DEFAULT
	}
	return p.Filter
}

var PageRequestDTO_Sort_DEFAULT string

func (p *PageRequestDTO) GetSort() (v string) {
	if !p.IsSetSort() {
		return PageRequestDTO_Sort_DEFAULT
	}
	return *p.Sort
}

var PageRequestDTO_Fields_DEFAULT []string

func (p *PageRequestDTO) GetFields() (v []string) {
	if !p.IsSetFields() {
		return PageRequestDTO_Fields_DEFAULT
	}
	return p.Fields
}

var PageRequestDTO_IncludeTotal_DEFAULT bool

func (p *PageRequestDTO) GetIncludeTotal() (v bool) {
	if !p.IsSetIncludeTotal() {
		return PageRequestDTO_IncludeTotal_DEFAULT
	}
	return *p.IncludeTotal
}

var PageRequestDTO_FetchAll_DEFAULT bool

func (p *PageRequestDTO) GetFetchAll() (v bool) {
	if !p.IsSetFetchAll() {
		return PageRequestDTO_FetchAll_DEFAULT
	}
	return *p.FetchAll
}

var fieldIDToName_PageRequestDTO = map[int16]string{
	1: "page",
	2: "limit",
	3: "search",
	4: "filter",
	5: "sort",
	6: "fields",
	7: "include_total",
	8: "fetch_all",
}

func (p *PageRequestDTO) IsSetPage() bool {
	return p.Page != PageRequestDTO_Page_DEFAULT
}

func (p *PageRequestDTO) IsSetLimit() bool {
	return p.Limit != PageRequestDTO_Limit_DEFAULT
}

func (p *PageRequestDTO) IsSetSearch() bool {
	return p.Search != nil
}

func (p *PageRequestDTO) IsSetFilter() bool {
	return p.Filter != nil
}

func (p *PageRequestDTO) IsSetSort() bool {
	return p.Sort != nil
}

func (p *PageRequestDTO) IsSetFields() bool {
	return p.Fields != nil
}

func (p *PageRequestDTO) IsSetIncludeTotal() bool {
	return p.IncludeTotal != nil
}

func (p *PageRequestDTO) IsSetFetchAll() bool {
	return p.FetchAll != nil
}

func (p *PageRequestDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.MAP {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageRequestDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PageRequestDTO) ReadField1(iprot thrift.TProtocol) error {

	var _field int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Page = _field
	return nil
}
func (p *PageRequestDTO) ReadField2(iprot thrift.TProtocol) error {

	var _field int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Limit = _field
	return nil
}
func (p *PageRequestDTO) ReadField3(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Search = _field
	return nil
}
func (p *PageRequestDTO) ReadField4(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return err
	}
	_field := make(map[string]string, size)
	for i := 0; i < size; i++ {
		var _key string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_key = v
		}

		var _val string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_val = v
		}

		_field[_key] = _val
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return err
	}
	p.Filter = _field
	return nil
}
func (p *PageRequestDTO) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Sort = _field
	return nil
}
func (p *PageRequestDTO) ReadField6(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]string, 0, size)
	for i := 0; i < size; i++ {

		var _elem string
		if v, err := iprot.ReadString(); err != nil {
			return err
		} else {
			_elem = v
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.Fields = _field
	return nil
}
func (p *PageRequestDTO) ReadField7(iprot thrift.TProtocol) error {

	var _field *bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.IncludeTotal = _field
	return nil
}
func (p *PageRequestDTO) ReadField8(iprot thrift.TProtocol) error {

	var _field *bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.FetchAll = _field
	return nil
}

func (p *PageRequestDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PageRequestDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageRequestDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetPage() {
		if err = oprot.WriteFieldBegin("page", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(p.Page); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PageRequestDTO) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetLimit() {
		if err = oprot.WriteFieldBegin("limit", thrift.I32, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(p.Limit); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageRequestDTO) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSearch() {
		if err = oprot.WriteFieldBegin("search", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Search); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *PageRequestDTO) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetFilter() {
		if err = oprot.WriteFieldBegin("filter", thrift.MAP, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.Filter)); err != nil {
			return err
		}
		for k, v := range p.Filter {
			if err := oprot.WriteString(k); err != nil {
				return err
			}
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteMapEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *PageRequestDTO) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetSort() {
		if err = oprot.WriteFieldBegin("sort", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Sort); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *PageRequestDTO) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetFields() {
		if err = oprot.WriteFieldBegin("fields", thrift.LIST, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Fields)); err != nil {
			return err
		}
		for _, v := range p.Fields {
			if err := oprot.WriteString(v); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *PageRequestDTO) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetIncludeTotal() {
		if err = oprot.WriteFieldBegin("include_total", thrift.BOOL, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBool(*p.IncludeTotal); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *PageRequestDTO) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetFetchAll() {
		if err = oprot.WriteFieldBegin("fetch_all", thrift.BOOL, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBool(*p.FetchAll); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *PageRequestDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageRequestDTO(%+v)", *p)

}

/**
 * 分页响应
 * 针对 REST API 优化的分页信息
 */
type PageResponseDTO struct {
	// 总记录数
	Total *int32 `thrift:"total,1,optional" json:"total,omitempty" form:"total" query:"total"`
	// 当前页码
	Page *int32 `thrift:"page,2,optional" json:"page,omitempty" form:"page" query:"page"`
	// 每页数量
	Limit *int32 `thrift:"limit,3,optional" json:"limit,omitempty" form:"limit" query:"limit"`
	// 总页数
	TotalPages *int32 `thrift:"total_pages,4,optional" json:"total_pages,omitempty" form:"total_pages" query:"total_pages"`
	// 是否有下一页
	HasNext *bool `thrift:"has_next,5,optional" json:"has_next,omitempty" form:"has_next" query:"has_next"`
	// 是否有上一页
	HasPrev *bool `thrift:"has_prev,6,optional" json:"has_prev,omitempty" form:"has_prev" query:"has_prev"`
}

func NewPageResponseDTO() *PageResponseDTO {
	return &PageResponseDTO{}
}

func (p *PageResponseDTO) InitDefault() {
}

var PageResponseDTO_Total_DEFAULT int32

func (p *PageResponseDTO) GetTotal() (v int32) {
	if !p.IsSetTotal() {
		return PageResponseDTO_Total_DEFAULT
	}
	return *p.Total
}

var PageResponseDTO_Page_DEFAULT int32

func (p *PageResponseDTO) GetPage() (v int32) {
	if !p.IsSetPage() {
		return PageResponseDTO_Page_DEFAULT
	}
	return *p.Page
}

var PageResponseDTO_Limit_DEFAULT int32

func (p *PageResponseDTO) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return PageResponseDTO_Limit_DEFAULT
	}
	return *p.Limit
}

var PageResponseDTO_TotalPages_DEFAULT int32

func (p *PageResponseDTO) GetTotalPages() (v int32) {
	if !p.IsSetTotalPages() {
		return PageResponseDTO_TotalPages_DEFAULT
	}
	return *p.TotalPages
}

var PageResponseDTO_HasNext_DEFAULT bool

func (p *PageResponseDTO) GetHasNext() (v bool) {
	if !p.IsSetHasNext() {
		return PageResponseDTO_HasNext_DEFAULT
	}
	return *p.HasNext
}

var PageResponseDTO_HasPrev_DEFAULT bool

func (p *PageResponseDTO) GetHasPrev() (v bool) {
	if !p.IsSetHasPrev() {
		return PageResponseDTO_HasPrev_DEFAULT
	}
	return *p.HasPrev
}

var fieldIDToName_PageResponseDTO = map[int16]string{
	1: "total",
	2: "page",
	3: "limit",
	4: "total_pages",
	5: "has_next",
	6: "has_prev",
}

func (p *PageResponseDTO) IsSetTotal() bool {
	return p.Total != nil
}

func (p *PageResponseDTO) IsSetPage() bool {
	return p.Page != nil
}

func (p *PageResponseDTO) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *PageResponseDTO) IsSetTotalPages() bool {
	return p.TotalPages != nil
}

func (p *PageResponseDTO) IsSetHasNext() bool {
	return p.HasNext != nil
}

func (p *PageResponseDTO) IsSetHasPrev() bool {
	return p.HasPrev != nil
}

func (p *PageResponseDTO) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageResponseDTO[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PageResponseDTO) ReadField1(iprot thrift.TProtocol) error {

	var _field *int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Total = _field
	return nil
}
func (p *PageResponseDTO) ReadField2(iprot thrift.TProtocol) error {

	var _field *int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Page = _field
	return nil
}
func (p *PageResponseDTO) ReadField3(iprot thrift.TProtocol) error {

	var _field *int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Limit = _field
	return nil
}
func (p *PageResponseDTO) ReadField4(iprot thrift.TProtocol) error {

	var _field *int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.TotalPages = _field
	return nil
}
func (p *PageResponseDTO) ReadField5(iprot thrift.TProtocol) error {

	var _field *bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.HasNext = _field
	return nil
}
func (p *PageResponseDTO) ReadField6(iprot thrift.TProtocol) error {

	var _field *bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.HasPrev = _field
	return nil
}

func (p *PageResponseDTO) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PageResponseDTO"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageResponseDTO) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetTotal() {
		if err = oprot.WriteFieldBegin("total", thrift.I32, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Total); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PageResponseDTO) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetPage() {
		if err = oprot.WriteFieldBegin("page", thrift.I32, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Page); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageResponseDTO) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetLimit() {
		if err = oprot.WriteFieldBegin("limit", thrift.I32, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Limit); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *PageResponseDTO) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetTotalPages() {
		if err = oprot.WriteFieldBegin("total_pages", thrift.I32, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.TotalPages); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *PageResponseDTO) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetHasNext() {
		if err = oprot.WriteFieldBegin("has_next", thrift.BOOL, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBool(*p.HasNext); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *PageResponseDTO) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetHasPrev() {
		if err = oprot.WriteFieldBegin("has_prev", thrift.BOOL, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBool(*p.HasPrev); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *PageResponseDTO) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResponseDTO(%+v)", *p)

}
